/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @author FusionCharts Technologies LLP
 @version fusioncharts/3.2.4-release.8565
*/
FusionCharts(["private","modules.renderer.highcharts-gradientlegend",function(){function aa(a,e,b){var h=a[0],f=a[1],a=a[2];h+=(e[0]-h)*b;f+=(e[1]-f)*b;e=a+(e[2]-a)*b;return{hex:(z+(h<<16|f<<8|e).toString(16)).slice(-6),rgb:[h,f,e]}}function n(a,e){return a.maxvalue-e.maxvalue}function $(a){var l=a.colorRange||{},h=a.dataMin,b=a.dataMax,f=a.sortLegend||!1,i=a.mapByCategory||!1,d=a.defaultColor,s=a.numberFormatter,c=l.color,a=this.colorArr=[],D,m,u,k,q;this.mapByCategory=i;if(l.mapbypercent==="1")this.mapbypercent=
!0;if(l.gradient==="1"&&!i){this.gradient=!0;D=e(S(l.startcolor,l.mincolor,l.code));f=qa(e(S(D,d,"CCCCCC")));i=this.scaleMin=I(l.startvalue,l.minvalue,this.mapbypercent?0:h);a.push({code:D,maxvalue:i,label:X(l.startlabel),codeRGB:qa(D)});if(c&&(m=c.length))for(h=0;h<m;h+=1)d=c[h],D=e(S(d.color,d.code)),k=I(d.value,d.maxvalue),q=I(d.minvalue),k>i&&a.push({code:D,maxvalue:k,userminvalue:q,label:X(S(d.label,d.displayvalue)),codeRGB:qa(D)});a.sort(n);m=a.length;for(h=1;h<m;h+=1)d=a[h],D=d.maxvalue-i,
D>0?(d.minvalue=i,d.range=D,i=d.maxvalue):(a.splice(h,1),h-=1,m-=1);if(a.length>=2)this.scaleMax=i,a[h-1].label=S(l.endlabel,a[h-1].label,a[h-1].displayvalue);if(a.length===1)k=I(l.maxvalue,this.mapbypercent?100:b),a.push({minvalue:i,maxvalue:k,range:k-i,label:l.endlabel}),this.scaleMax=k,delete a[0].code;l=a[0];b=a[a.length-1];if(!l.code||!b.code){m=ha(f);m={minRGB:va((m[2]=0,m)),maxRGB:va((m[2]=100,m))};if(!l.code)l.codeRGB=m.minRGB,l.code=wa(m.minRGB);if(!b.code)b.codeRGB=m.maxRGB,b.code=wa(m.maxRGB)}m=
a.length;for(h=1;h<m;h+=1)if(d=a[h],d.code){if(u){b=d;q=l.maxvalue;for(c=b.maxvalue-q;u<h;u+=1)f=a[u],D=aa(l.codeRGB,b.codeRGB,(f.maxvalue-q)/c),f.code=D.hex,f.codeRGB=D.rgb}u=null;l=d}else u=u||h;if(this.scaleMin===void 0||this.scaleMax===void 0)this.noValidRange=!0}else if(c&&(m=c.length)){for(h=0;h<m;h+=1)d=c[h],D=S(d.color,d.code),k=I(d.maxvalue),q=I(d.minvalue),u=S(d.label,d.displayvalue,i?V:s.dataLabels(q)+" - "+s.dataLabels(k)),(D&&k>q||i&&u)&&a.push({code:D,maxvalue:k,minvalue:q,label:X(u),
labelId:u.toLowerCase()});a.length?f&&a.sort(n):this.noValidRange=!0}}function Y(e,h){return h?j(e*100)/100+a:ra(e,V).toString()}var b=this.hcLib,I=b.pluckNumber,z=b.COLOR_BLACK,g=b.COLOR_GLASS,sa=b.FC_CONFIG_STRING,ea=b.graphics,va=ea.HSBtoRGB,ha=ea.RGBtoHSB,wa=ea.RGBtoHex,qa=ea.HEXtoRGB,ba=b.COMMASTRING,V=b.BLANKSTRING,X=b.parseUnsafeString,p=b.graphics.convertColor,r=b.POSITION_RIGHT,la=b.POSITION_LEFT,fa=b.POSITION_CENTER,xa=b.graphics.getDarkColor,ta=b.graphics.getLightColor,S=b.pluck,ra=b.getValidValue,
M=b.Highcharts,ea=M.legendTypes,za=M.hasTouch,na=M.getTouchEvent,ya=M.getPosition,T=M.addEvent,j=Math.round,G=Math.max,Q=Math.min,o=Math.abs,a="%",h={pageX:0,pageY:0},e=function(a){return a&&a.replace(/^#?([a-f0-9]+)/ig,"$1")};$.prototype={getColorObj:function(a){var e=this.colorArr,h=this.gradient?1:0,b=e[h];if(this.mapByCategory){for(a=X(a).toLowerCase();b;){if(b.labelId===a)return{code:b.code,seriesIndex:h};h+=1;b=e[h]}return{outOfRange:!0}}else if(this.gradient)if(this.scaleMin<=a&&this.scaleMax>=
a){for(;b&&b.maxvalue<a;)h+=1,b=e[h];a=(a-b.minvalue)/b.range;return{code:aa(e[h-1].codeRGB,b.codeRGB,a).hex}}else return{outOfRange:!0};else{for(;b;){if(b.maxvalue>=a&&b.minvalue<=a)return{code:b.code,seriesIndex:h};h+=1;b=e[h]}return{outOfRange:!0}}}};$.prototype.constructor=$;b.colorRange=$;var U=b.configureGradientLegendOptions=function(a,e){var h=a.legend,b=e.chart;h.legendSliderBorderWidth=I(b.legendpointerborderthickness,1);h.legendSliderBorderColor=p(S(b.legendpointerbordercolor,z),I(b.legendpointerborderalpha,
100));h.legendSliderWidth=I(b.legendpointerwidth,b.legendpointerswidth,12);h.legendSliderHeight=I(b.legendpointerheight,b.legendpointersheight,12);h.legendColorBoxBorderColor=h.borderColor;h.legendColorBoxBorderWidth=h.borderWidth;h.legendScaleColor=p(S(b.legendscalelinecolor,z),I(b.legendscalelinealpha,100));h.legendScalePadding=I(b.legendscalepadding,4);h.legendScaleLineThickness=I(b.legendscalelinethickness,1);h.legendScaleTickDistance=I(b.legendscaletickdistance,6);h.itemStyle.cursor="default";
h.interActivity=I(b.interactivelegend,1)};b.placeGLegendBlockRight=function(a,h,e,g,f){b.configureLegendOptions(a,h.chart,!0,f,e);U(a,h);var f=a[sa].smartLabel,i=a.legend,d,s,c=i.textPadding=2,D=c*2,m=i.title.padding,u=0,k=0,q=2*i.padding,h=I(h.chart.legendpadding,7)+i.borderWidth/2+1,F=a.colorRange||{},t=F.colorArr,ca=F.mapbypercent,oa=F.scaleMin,Ga=F.scaleMax-oa,x=i.legendSliderWidth,A=i.legendSliderHeight/2,K=i.legendScalePadding,y=i.legendScaleTickDistance;s=i.itemStyle||{};var w=I(parseInt(s.lineHeight,
10)||12),p=w*0.75,j=e-q,C,H,n=0,r,o,E,R,z,S;g-=q;if(!F.noValidRange&&t&&(H=t.length)>1){H-=1;if(i.title.text!==V)f.setStyle(i.title.style),k=f.getSmartText(i.title.text,j,G(w,g/4)),i.title.text=k.text,u=k.width+q,g-=k=k.height+m;j-=y+K+x;i.colorBoxX=x;m=G(w,j/2);j=Q(j-m-4,w);r=G(w,g/2);C=g/4;f.setStyle(s);w=t[0];w.scaleLabel=Y(w.maxvalue,ca);d=f.getSmartText(w.label,C,j);w.label=d.text;K=d.height;w.labelY=p-d.height/2;s=f.getSmartText(w.scaleLabel,m,r);w.scaleLabel=s.text;y=s.height/2;F=s.width;w.scaleLabelY=
p-s.height/2;i.colorBoxY=G(y,d.width+D,A)+k;w=S=t[H];w.scaleLabel=Y(w.maxvalue,ca);d=f.getSmartText(w.label,C,j);w.label=d.text;K=G(K,d.height);w.labelY=p-d.height/2;s=f.getSmartText(w.scaleLabel,m,r);w.scaleLabel=s.text;F=G(F,s.width);C=s.height/2;A=G(d.width+D,C,A);w.scaleLabelY=p-s.height/2;i.colorBoxHeight=A=g-i.colorBoxY-A;r=A-C;o=A/Ga;R=Q(A-n,r-y)-4;for(C=1;C<H;C+=1)w=t[C],E=(w.maxvalue-oa)*o,d=f.getSmartText(w.label,Q(E-n,A-E)*2,j),w.label=d.text,K=G(K,d.height),w.labelY=p-d.height/2,d=d.width/
2,w.scaleLabel=Y(w.maxvalue,ca),s=f.getSmartText(w.scaleLabel,m,Q(E-y,r-E)*2),w.scaleLabel=s.text,F=G(F,s.width),z=s.height/2,w.scaleLabelY=p-s.height/2,R=Q(R,(E-G(z+y,d+n)-4)*Ga/w.range),n=d+E,y=z+E;R=G(Q(R,(Q(r-y,A-n)-4)*Ga/S.range,g*0.3),0);i.colorBoxHeight-=R;i.colorBoxWidth=K&&K+D||15;i.height=i.totalHeight=g+k+q-R;i.width=(F&&F+c)+i.colorBoxWidth+x+i.legendScaleTickDistance+i.legendScalePadding+q;if(i.width<u)i.colorBoxX+=(u-i.width)/2,i.width=u;if(i.width>e)i.width=e;h+=i.width;a.chart.marginRight+=
h;return h}else return i.enabled=!1,0};b.placeGLegendBlockBottom=function(a,h,e,g,f){b.configureLegendOptions(a,h.chart,!1,f,e);U(a,h);var f=a[sa].smartLabel,i=a.legend,d,s,c=i.textPadding=2,D=i.title.padding,m=0,u=0,k=2*i.padding,h=I(h.chart.legendpadding,7)+i.borderWidth/2+1,q=a.colorRange||{},F=q.colorArr,t=q.mapbypercent,ca=q.scaleMin,oa=q.scaleMax-ca,p=i.legendSliderWidth,x=i.legendSliderHeight,A=i.legendScalePadding,K=i.legendScaleTickDistance,y=i.itemStyle||{},w=I(parseInt(y.lineHeight,10)||
12),j=w*0.75,r=g-k,C,n,o,z=0,T,E,R;e-=k;if(!q.noValidRange&&F&&(n=F.length)>1){n-=1;if(i.title.text!==V)f.setStyle(i.title.style),u=f.getSmartText(i.title.text,e,r/3),i.title.text=u.text,m=u.width+k,r-=u=u.height+D;r-=K+A+x;D=G(w,r/2);w=Q(r-D-4,w);f.setStyle(y);C=e/4;o=C*2;q=F[0];q.scaleLabel=Y(q.maxvalue,t);d=f.getSmartText(q.label,C,w);q.label=d.text;y=d.height;q.labelY=j-d.height/2;s=f.getSmartText(q.scaleLabel,o,D);q.scaleLabel=s.text;r=s.width/2;A=s.height;if(!q.code)q.code=S(i.minColor,"CCCCCC");
i.colorBoxX=G(r,d.width+c,p);q=K=F[n];q.scaleLabel=Y(q.maxvalue,t);d=f.getSmartText(q.label,C,w);q.label=d.text;y=G(y,d.height);q.labelY=j-d.height/2;s=f.getSmartText(q.scaleLabel,o,D);q.scaleLabel=s.text;A=G(A,s.height);q=s.width/2;p=G(d.width+c,q,p);i.colorBoxWidth=p=e-i.colorBoxX-p;o=p-q;T=p/oa;R=Q(p-z,o-r)-4;for(C=1;C<n;C+=1)q=F[C],E=(q.maxvalue-ca)*T,d=f.getSmartText(q.label,Q(E-z,p-E)*2,w),q.label=d.text,y=G(y,d.height),q.labelY=j-d.height/2,d=d.width/2,q.scaleLabel=Y(q.maxvalue,t),s=f.getSmartText(q.scaleLabel,
Q(E-r,o-E)*2,D),q.scaleLabel=s.text,A=G(A,s.height),s=s.width/2,R=Q(R,(E-G(s+r,d+z)-4)*oa/q.range),z=d+E,r=s+E;R=G(Q(R,(Q(o-r,p-z)-4)*oa/K.range,e*0.3),0);i.colorBoxWidth-=R;i.width=e+k-R;if(i.width<m)i.colorBoxX+=(m-i.width)/2,i.width=m;i.colorBoxY=u+x;i.colorBoxHeight=y&&y+2*c||15;i.height=i.totalHeight=(A&&A+c)+i.colorBoxHeight+u+x+i.legendScaleTickDistance+i.legendScalePadding+k;if(i.height>g)i.height=g;h+=i.height;a.chart.marginBottom+=h;return h}else return i.enabled=!1,0};var oa=function(){return{point:this}},
M=M.extendClass(ea.point,{colorizeItem:function(){},destroy:function(){var a=this.elements,h=a.box,e=a.legendGroup,b=a.legendScroller,f=a.legendClip,i=a.colorBox,d=a.colorBoxEffect,s=a.slider1,c=a.slider1Effect,D=a.slider2,m=a.slider2Effect;if(i)a.colorBox=i.destroy();if(d)a.colorBoxEffect=d.destroy();if(s)a.slider1=s.destroy();if(c)a.slider1Effect=c.destroy();if(D)a.slider2=D.destroy();if(m)a.slider2Effect=m.destroy();if(h)a.box=h.destroy();if(e)a.legendGroup=e.destroy();if(b)a.legendScroller=b.destroy();
if(f)a.legendClip=f.destroy()},renderAllItems:function(){var a=this.chart,e=a.plotLeft,b=a.plotTop,U=a.plotWidth,f=a.plotHeight,i=a.tooltip,d=a.options.colorRange,s,c,D,m,u=this.conf,k=u.fontSize,q=u.padding,F=this.renderer,t=this.options,ca=t.itemStyle,pa=t.symbolStyle,n=t.interActivity,x=this.elements,A=x.legendGroup,K=u.horizontal,y,w,ja,G,C,H,u=0,I=t.lighting3d,aa,X,E=t.colorBoxX,R=t.colorBoxY,ia=aa=t.colorBoxWidth,M=X=t.colorBoxHeight,$=this.allItems,ea={FCcolor:{color:V,alpha:V,angle:0,ratio:V}},
ma=ea.FCcolor;E+=q;var q=R+q,N,R=t.legendColorBoxBorderColor,Y=t.legendColorBoxBorderWidth,Aa=["M"],La=t.legendScaleColor;C=t.legendScalePadding;var ha=t.legendScaleLineThickness,ua=ha%2/2;c=t.legendScaleTickDistance;N=t.legendSliderWidth;y=t.legendSliderHeight;m=M/2;H=ia/2;var B=N/2,L=y/2,ka,da,ga,O,W;ja=0;Q(N,y);var Ba=ta("ABABAB",50),Ca=xa("ABABAB",70),t=p("ABABAB",100),Ca=p(Ca,100),Ba=p(Ba,100),Ha,P={isFirst:!0},J={},Da,Ea,Ia=a.series,Ja;if(d&&(s=d.colorArr)&&(D=s.length)>1){P.toolText=Da=w=d.scaleMin;
J.toolText=Ea=ja=d.scaleMax;G=ja-w;P.snapPX=J.snapPX=0;P.tooltipConstraint=J.tooltipConstraint="chart";P.getLabelConfig=J.getLabelConfig=oa;P.series=J.series={};P.tooltipPos=[0,0];J.tooltipPos=[0,0];J.tooltipOffsetReference=P.tooltipOffsetReference=ya(a.container);J.tooltipOffsetReference.left=P.tooltipOffsetReference.left+=e-20;J.tooltipOffsetReference.top=P.tooltipOffsetReference.top+=b;if(K){P.tooltipPos[1]=J.tooltipPos[1]=f+b;U=j(E-B)+0.5;f=j(E+B)+0.5;d=j(q-y)+0.5;y=j(q+M)+0.5;ka=j(E-2)+0.5;N=
j(E+2)+0.5;da=j(E)+0.5;ga=j(q)+0.5;O=q-L/2;W=j(O-L)+0.5;O=j(O)+0.5;ja=E-B/2;H=j(ja+B)+0.5;ja=j(ja)+0.5;X/=2;B=["M",U,d,"L",f,d,f,ga,N,ga,da,y,ka,ga,U,ga,"Z","M",ja,W,"L",ja,O,"M",da,W,"L",da,O,"M",H,W,"L",H,O];L=["M",U,d+1,"L",f,d+1,"M",ja-1,W,"L",ja-1,O,"M",da-1,W,"L",da-1,O,"M",H-1,W,"L",H-1,O];C=q+M+C;ja=j(C+c)+ua;C=j(C)+ua;d=ja+k;N=q+m;f=D-1;for(c=0;c<D;c+=1)m=s[c],H=(m.maxvalue-w)/G,y=ia*H+E,k=j(y)+ua,c?(ma.ratio+=ba,ma.color+=ba,ma.alpha+=ba,Aa.push("L",k,C,k,ja,"M",k,C),c===f?(U=la,k=y+2):
(U=fa,k=y)):(Aa.push(k,C,"L",k,ja,"M",k,C),U=r,k=y-2),ma.ratio+=(H-u)*100,ma.color+=S(m.code,z),ma.alpha+=S(m.alpha,100),u=H,m.legendItem=F.text(m.label,k,N+m.labelY).css(ca).attr({zIndex:3,align:U}).add(A),m.legendSymbol=F.text(m.scaleLabel,y,d).css(ca).attr({zIndex:2,align:fa}).add(A),$.push(m);P.xMin=J.xMin=0;P.xMax=J.xMax=ia;P.yMin=J.yMin=0;P.yMax=J.yMax=0;P.y=J.y=0;P.x=0;J.x=ia}else{P.tooltipPos[0]=J.tooltipPos[0]=U+e;ja=270;ma.angle=90;U=E-N;f=E+ia;d=q-L;y=q+L;U=j(E-N)+0.5;f=j(E)+0.5;d=j(q-
L)+0.5;y=j(q+L)+0.5;ka=j(E+ia)+0.5;ga=j(q-2)+0.5;O=j(q+2)+0.5;W=j(q)+0.5;N=E-B/2;da=j(N-L)+0.5;N=j(N)+0.5;k=q-L/2;m=j(k+L)+0.5;k=j(k)+0.5;aa/=2;B=["M",U,d,"L",f,d,f,ga,ka,W,f,O,f,y,U,y,"Z","M",da,k,"L",N,k,"M",da,W,"L",N,W,"M",da,m,"L",N,m];L=["M",U+1,d,"L",U+1,y,"M",da,k-1,"L",N,k-1,"M",da,W-1,"L",N,W-1,"M",da,m-1,"L",N,m-1];k=E+ia+C;d=j(k+c)+ua;k=j(k)+ua;N=E+H;f=D-1;for(c=0;c<D;c+=1)m=s[c],H=(m.maxvalue-w)/G,y=M*H+q,C=j(y)+ua,c?(ma.ratio+=ba,ma.color+=ba,ma.alpha+=ba,Aa.push("L",k,C,d,C,"M",k,C),
c===f?(U=r,C=y+2):(U=fa,C=y)):(Aa.push(k,C,"L",d,C,"M",k,C),U=la,C=y-2),ma.ratio+=(H-u)*100,ma.color+=S(m.code,z),ma.alpha+=S(m.alpha,100),u=H,m.legendItem=F.text(m.label,N+m.labelY,C).css(ca).attr({zIndex:3,align:U,rotation:ja}).add(A),m.legendSymbol=F.text(m.scaleLabel,d,y+m.scaleLabelY).css(ca).attr({zIndex:2,align:la}).add(A),$.push(m);P.xMin=J.xMin=0;P.xMax=J.xMax=0;P.yMin=J.yMin=0;P.yMax=J.yMax=M;P.x=J.x=0;P.y=0;J.y=M}x.colorBox=F.rect(E,q,ia,M,0,1).attr({zIndex:2,fill:ea,stroke:R,strokeWidth:Y}).add(A);
if(I)x.colorBoxEffect=F.rect(E,q,aa,X,0,1).attr({zIndex:2,fill:g,strokeWidth:0}).add(A);x.scale=F.path(Aa).attr({zIndex:2,stroke:La,strokeWidth:ha}).add(A);Ha=function(a,c,f){var d,i=0,h=Ia&&Ia.length,k;K?(d=a*G/ia+w,a=a||0.01):(d=c*G/M+w,c=c||0.01);f?(x.slider1.translate(a,c).toFront(),x.slider1Effect.translate(a,c).toFront(),Da=d,P.toolText=j(Da*100)/100):(x.slider2.translate(a,c).toFront(),x.slider2Effect.translate(a,c).toFront(),Ea=d,J.toolText=j(Ea*100)/100);n&&(Ja=clearTimeout(Ja),Ja=setTimeout(function(){for(;i<
h;i+=1)k=Ia[i],k.setScaleRange&&k.setScaleRange(Da,Ea)},100))};s=function(c){var f=c.data,d=za&&na(c)||h,k,m=k=0,q,s=f.isFirst,u=s?J:P;if(c.type==="dragstart")f.tooltipOffsetReference=ya(a.container),f.tooltipOffsetReference.left+=e-20,f.tooltipOffsetReference.top+=b,f.lastDraggedX=f.dragStartX=c.pageX||d.pageX,f.lastDraggedY=f.dragStartY=c.pageY||d.pageY;else{if(K){k=f.x+((c.pageX||d.pageX)-f.dragStartX);k<=0&&(k=0);k>ia&&(k=ia);if(s?k>u.x:k<u.x)k=u.x;if(o(k-f.lastDraggedX)>=(f.snapPX||0))q=!0}else{m=
f.y+((c.pageY||d.pageY)-f.dragStartY);m<=0&&(m=0);m>M&&(m=M);if(s?m>u.y:m<u.y)m=u.y;if(o(m-f.lastDraggedY)>=(f.snapPX||0))q=!0}if(c.type==="drag"){if(q)f.lastDraggedX=k,f.lastDraggedY=m,Ha(k,m,s),Fa(c,!0)}else delete f.lastDraggedX,delete f.lastDraggedY,delete f.dragStartX,delete f.dragStartY,f.x=k,f.y=m,Ha(k,m,s),i&&i.hide()}};x.slider1=F.path(B).attr({zIndex:3,fill:t,strokeWidth:1,stroke:Ca}).css(pa).add(A);x.slider1Effect=F.path(L).attr({zIndex:3,fill:"none",strokeWidth:1,stroke:Ba}).css(pa).add(A);
x.slider2=F.path(B).attr({zIndex:3,fill:t,strokeWidth:1,stroke:Ca}).css(pa).add(A).translate(J.x,J.y);x.slider2Effect=F.path(L).attr({zIndex:3,fill:"none",strokeWidth:1,stroke:Ba}).css(pa).translate(J.x,J.y).add(A);T(x.slider1.element,"dragstart dragend drag",s,P);T(x.slider1Effect.element,"dragstart dragend drag",s,P);T(x.slider2.element,"dragstart dragend drag",s,J);T(x.slider2Effect.element,"dragstart dragend drag",s,J);var Fa=function(a,c){var f=a.data,d=f.tooltipOffsetReference;if((c||f.lastDraggedX===
void 0)&&i)K?f.tooltipPos[0]=(a.pageX||a.x||a.offsetX)-d.left:f.tooltipPos[1]=(a.pageY||a.y||a.offsetY)-d.top,i.refresh(f)},F=function(a){a.data.lastDraggedX===void 0&&i&&i.hide()};T(x.slider1.element,"mouseout",F,P);T(x.slider1Effect.element,"mouseover",Fa,P);T(x.slider1Effect.element,"mouseout",F,P);T(x.slider2.element,"mouseover",Fa,J);T(x.slider2.element,"mouseout",F,J);T(x.slider2Effect.element,"mouseover",Fa,J);T(x.slider2Effect.element,"mouseout",F,J)}}});ea.gradient=M}]);
FusionCharts(["private","modules.renderer.highcharts-annotations",function(){var aa=this.core,n=this.hcLib,$=n.Highcharts,Y=$.each,b=$.addEvent,I=$.removeEvent,z=$.hasTouch,g=$.hasSVG,sa=z?6:5,ea="rgba(192,192,192,"+(g?1.0E-6:0.0020)+")",va=Math.min,ha=Math.max,wa=Math.sin,qa=Math.cos,ba=Math.PI,V=ba/180,X=this.extend,p=n.pluck,r=n.pluckNumber,la=n.graphics.convertColor,fa=n.getDashStyle,xa=n.getValidValue,ta=n.parseUnsafeString,S=n.setImageDisplayMode,ra=n.graphics.parseColor,M=n.setLineHeight,za=
{style:{}},na=function(){return this},ya=function(a,h){var e;if(h>360||h<-360)h%=360;if(a>360||a<-360)a%=360;e=a-h;if(e>360||e<-360)e%=360,h=a-e;h=360-h;a=360-a;if(a>360||h>360)a-=360,h-=360;return{start:a,end:h,angle:-e}},T=function(a,h,e,b){var g=0,v=0,h=h===void 0||h===null?1:h,l;if(!a||!a.toString)return e;a=a.toLowerCase().replace(/\s/g,"");if(e=a.match(/^[\+\-]?\d+(\.\d+)?|[\+\-]\d+(\.\d+)?/g)){for(l=0;l<e.length;l+=1)g+=Number(e[l])||0;g*=h}if(e=a.match(/^[\+\-]?(\$[a-z]+)|[\+\-](\$[a-z]+)/g))for(l=
0;l<e.length;l+=1)v+=b[e[l]]||0;if(e=a.match(/^[\+\-]?\$\d+(\.\d+)?|[\+\-]\$\d+(\.\d+)?/g))for(l=0;l<e.length;l+=1)v=v+Number(e[l].replace("$",""))||0;return g+v},j=function(a){var h=this.__state.annotationGroupsById;(a=h&&h[a])&&a.wrapper&&a.wrapper.show()},G=function(a){var h=this.__state.annotationGroupsById;(a=h&&h[a])&&a.wrapper&&a.wrapper.hide()},Q,o;Q=function(a,h,e,b){this.options=a;this.chart=e;this.attrs={};this.css={};this.bounds={};this.shared=h;this.snaps=b||{};this.id=a.id||"";this.items=
[];this.setup();this.scale()};X(Q.prototype,{scaleImageX:1,scaleImageY:1,scaleText:1,scaleValue:1,scaleValueComplement:1,scaleX:1,scaleY:1});Q.prototype.setup=function(){var a=this.options;this.isBelow=p(a.showbelow,a.showbelowchart,this.shared.showbelow)!="0";this.useTracker=!this.isBelow&&this.chart.trackerGroup&&this.shared.useTracker};Q.prototype.scale=function(){var a=this.options,h=this.chart,e=this.shared,b=this.bounds,g=this.snaps,v=e.rootxscale,l=e.rootyscale,Z=b.xs=r(a.xscale,e.xscale,100)/
100,j=b.ys=r(a.yscale,e.yscale,100)/100,f,i,d;this.scaleText*=j;this.scaleImageX*=Z;this.scaleImageY*=j;if(p(a.autoscale,e.autoscale)!="0")Z=r(a.origw,e.origw),j=r(a.origh,e.origh),Z=h.chartWidth/Z,j=h.chartHeight/j,h=p(a.constrainedscale,e.constrainedscale)!="0",f=Z<j?Z:j,i=h?f:Z,d=h?f:j,this.scaleValue*=f,this.scaleValueComplement*=h?f:Z<j?j:Z,this.scaleX*=i,this.scaleY=this.scaleX*d,b.xs*=i,b.ys*=d,v*=i,l*=d,p(a.scaletext,e.scaletext)=="1"&&(this.scaleText*=d),p(a.scaleimages,e.scaleimages)=="1"&&
(this.scaleImageX*=i,this.scaleImageY*=d);b.x=T(p(a.x,a.xpos),v,0,g)+r(a.grpxshift,e.grpxshift,0);b.y=T(p(a.y,a.ypos),l,0,g)+r(a.grpyshift,e.grpyshift,0);this.xshift=r(a.xshift,e.xshift,0);this.yshift=r(a.yshift,e.yshift,0)};Q.prototype.draw=function(){var a=this.chart,h=this.options,e=this.bounds,b=this.items,g;if(!this.wrapper)this.wrapper=a.renderer.g("annotations").attr({zIndex:this.isBelow?0.5:6}).add();for(this.wrapper.attr({x:0,y:0,visibility:h.visible=="0"?"hidden":""}).translate(e.x,e.y);e=
b.unshift();)e.destroy();if(h=h.items){e=0;for(g=h.length;e<g;e+=1)b.push((new o(a,h[e],this)).draw())}return this};Q.prototype.destroy=function(){for(var a=this.wrapper,h=this.items,e;e=h.shift();)e.destroy();if(a)this.wrapper=a.destroy()};o=function(a,h,e){var b=!1,g;this.chart=a;this.options=h;this.group=e;this.args=[];this.attrs={};this.attrsTracker={};this.style={};this.bounds={};this.type=h.type&&h.type.toLowerCase&&h.type.toLowerCase();for(g in o.eventNames)typeof h[g]==="function"&&(this[g]=
h[g],b=!0);this.hasEvents=b;if(typeof h.onload==="function")this.onload=h.onload;this.scale();this.setup()};o.prototype.getAbsoluteBounds=function(){var a=this.bounds,h=a.x1,e=a.y1,b=a.x2,g=a.y2,v=va(h,b),l=va(e,g),h=ha(h,b)-v,e=ha(e,g)-l;return{x:v,width:h,y:l,height:e,r:a.r,unscaled:{width:h/a.xs,height:e/a.ys}}};o.prototype.scale=function(){var a=this.group,h=a.bounds,e=this.bounds,b=this.options,g=a.snaps,v=p(b.x,b.xpos),l=p(b.y,b.ypos),j=p(b.tox,b.toxpos),n=p(b.toy,b.toypos),f=e.xs=h.xs,h=e.ys=
h.ys,i=r(b.xshift,a.xshift,0),d=r(b.yshift,a.yshift,0);this.hasDimensionY=this.hasDimensionX=this.hasDimension=!0;e.x1=T(v,f,0,g)+i;j===void 0?(this.hasDimensionX=this.hasDimension=!1,e.x2=e.x1):e.x2=T(j,f,0,g)+i;e.y1=T(l,h,0,g)+d;n===void 0?(this.hasDimensionY=this.hasDimension=!1,e.y2=e.y1):e.y2=T(n,h,0,g)+d;e.r=r(b.radius,0)*a.scaleValue};o.prototype.setup=function(){var a=this.options,b=this.group,e=b.options,g=this.attrs,oa=this.style,v=b.scaleValue,l=r(e.fillalpha,e.alpha,100),j=this.fillAlpha=
p(a.fillalpha,a.alpha,l),n=this.fillColor=p(a.fillcolor,a.color,e.color,"#ff0000"),f=this.fillPattern=p(a.fillpattern&&a.fillpattern.toLowerCase&&a.fillpattern.toLowerCase(),e.fillpattern&&e.fillpattern.toLowerCase&&e.fillpattern.toLowerCase()),i=a.showborder?a.showborder=="1":xa(a.bordercolor),d=this.borderAlpha=r(a.borderalpha,a.alpha,e.borderalpha,l),l=this.dashed=a.dashed=="1";this.link=p(a.link,e.link);this.shadow=p(a.showshadow,e.showshadow)=="1";g.stroke=i?la(p(a.bordercolor,n),d):"none";g["stroke-linecap"]=
"round";j={FCcolor:{gradientUnits:"objectBoundingBox",color:n,alpha:j,ratio:p(a.fillratio,e.fillratio),angle:360-r(a.fillangle,0),radialGradient:f==="radial"}};g.fill=j;g["stroke-width"]=i?r(a.borderthickness,a.thickness,2)*v:0;if(l)g.dashstyle=fa(a.dashlen*v,a.dashgap*v,g["stroke-width"]);if(this.link)oa.cursor="pointer",oa._cursor="hand";this.useTracker=b.useTracker;this.toolText=ta(p(a.tooltext,e.tooltext));(this.useTracker||this.link||this.toolText)&&X(this.attrsTracker,{isTracker:+new Date,stroke:ea,
fill:ea})};o.prototype.draw=function(){var a=this,h=a.chart,e=a.type,g=a.attrs,j=a.style,v=h.renderer,e=o.types[e]&&o.types[e].call&&o.types[e].call(a),l=e==="image",p=e==="text",r=l||p,f=a.link||a.toolText,i=a.wrapper,d=a.tracker,s=!1,c,D,m=o.eventNames,u,k;if(e){if(i)if(i.elemType!==e)i=i.destroy();else if(a.hasEvents)for(u in m)if((k=a[u])&&k.eventAttached)I(D.element,m[u],k),k.eventAttached=!1;i?i.attr(g).css(j):(i=a.wrapper=v[e].apply(h.renderer,a.args).attr(g).css(j).add(a.group.wrapper),i.elemType=
e,s=!0);a.shadow&&!a.shadowAdded&&!l&&!p?(c={opacity:ha(a.borderAlpha,g.fill.FCcolor.alpha)/100},a.shadowAdded=!0,i.shadow(c,void 0,c)):(a.shadowAdded=!1,(c=i.shadows)&&Y(c,function(a){i.safeRemoveChild(a)}));p&&i.textBound();if(f){if(a.useTracker){if(!d)d=a.tracker=r?v.rect(0,0,0,0,0):v[e].apply(h.renderer,a.args);d.attr(g).attr(a.attrsTracker);d.added||d.add(h.trackerGroup)}a.toolText&&a.createTooltip()}else d&&(d=d.destroy());D=a.tracker||i;if(a.link)D.on("click",function(){h.options.instanceAPI.linkClickFN.call(a)});
if(a.hasEvents)for(u in m)if((k=a[u])&&!k.eventAttached)b(D.element,m[u],k,a),k.eventAttached=!0;l||(d&&r&&d.attr(i.getBBox()),s&&a.onload&&a.onload(g))}return a};o.prototype.createTooltip=function(a){var b=this.wrapper,e=this.chart,g=e.plotLeft,j=e.plotTop,v,l,p,r,f,i=!1;if(v=e.tooltip)a||(a=this.tracker||b),l={tooltipPos:[20,20],series:{},svgElm:b.svgElm,point:this,getLabelConfig:na},p=function(){v.refresh(l)},r=function(){v.hide()},a.on("mousemove",function(a){l.tooltipPos[0]=(a.layerX||a.x)-g;
l.tooltipPos[1]=(a.layerY||a.y)-j;i&&f&&(f=clearTimeout(f));i=!1;f?(f=clearTimeout(f),f=setTimeout(p,150)):(v.refresh(l),f=-2)}).on("mouseout",function(){f=clearTimeout(f);i=!0;f=setTimeout(r,200)})};o.prototype.destroy=function(){var a=this.wrapper;if(a)this.tracker&&this.tracker.destroy(),this.wrapper=a.destroy()};o.eventNames={onmouseover:z?"touchstart":"mouseover",onmouseout:"mouseout",onmousemove:z?"touchmove":"mousemove",onclick:"click"};o.textAlignOptions={left:"left",right:"right",center:"center"};
o.textVerticalAlignOptions={top:"top",middle:"middle",bottom:"bottom"};o.textRotationOptions={0:"0",1:"270",right:"90",left:"270"};o.types={rectangle:function(){var a=this.args,b=this.getAbsoluteBounds(),e=b.width*0.5;if(b.r>e)b.r=e;a[0]=b.x;a[1]=b.y;a[2]=b.width;a[3]=b.height;a[4]=b.r;return"rect"},line:function(){var a=this.options,b=this.group.scaleValue,e=this.attrs,g=this.bounds;this.args[0]=["M",g.x1,g.y1,"L",g.x2,g.y2];e.stroke=la(this.fillColor,this.fillAlpha);e["stroke-width"]=r(a.thickness,
2)*b;e["stroke-width"]<sa&&(this.attrsTracker["stroke-width"]=sa);this.attrsTracker.dashstyle="solid";return"path"},polygon:function(){var a=this.args,b=this.options,e=this.bounds;a[0]="poly_"+r(b.sides,5);a[1]=e.x1;a[2]=e.y1;a[3]=e.r;a[4]={startAngle:r(b.startangle,0)*V};return"symbol"},circle:function(){var a=this.args,b=this.attrs,e=this.options,g=this.bounds,j=this.chart.chartWidth,v=this.chart.chartHeight,l=this.group.scaleValueComplement,n=ya(r(e.startangle,0),r(e.endangle,360)),o=g.r,f,i;if(!p(e.radius))g.r=
j<v?j*g.xs:v*g.ys,g.r=o=g.r*0.3;e=r(e.yradius,o/l)*l;if(!this.fillPattern)b.fill.FCcolor.radialGradient=!0,this.fillPattern="radial";if(this.fillPattern==="radial")b.fill.FCcolor.cx=b.fill.FCcolor.cy=0.5;if(!(n.angle%360)&&o===e)return a[0]=g.x1,a[1]=g.y1,a[2]=g.r,"circle";n.angle%360||(n.start-=0.0010);b=this.chart.renderer.getArcPath;f=n.start*V;j=n.end*V;n=n.angle*V;v=g.x1;l=g.y1;g=v+qa(f)*o;f=l+wa(f)*e;i=v+qa(j)*o;j=l+wa(j)*e;o=b(v,l,g,f,i,j,o,e,0,n>=ba?1:0);o.unshift("M",g,f);o.push("Z");a[0]=
o;return"path"},arc:function(){var a=this.options,b=this.args,e=this.attrs,j=this.bounds,n=this.chart.chartWidth,v=this.chart.chartHeight,l=this.group.scaleValue,o=ya(r(a.startangle,0),r(a.endangle,360)),z=o.start,f=o.end;if(!p(a.radius))j.r=n<v?n*j.xs:v*j.ys,j.r*=0.3;j.innerR=r(a.innerradius,j.r*0.8/l)*l;if(j.innerR>j.r)j.innerR+=j.r,j.r=j.innerR-j.r,j.innerR-=j.r;!(o.angle%360)&&!g&&(f+=0.5,z-=0.5);if(!this.fillPattern)e.fill.FCcolor.radialGradient=!0,this.fillPattern="radial";if(this.fillPattern===
"radial")e.fill.FCcolor.cx=e.fill.FCcolor.cy=0.5;b[0]=j.x1;b[1]=j.y1;b[2]=j.r;b[3]=j.innerR;b[5]=z*V;b[4]=f*V;return"arc"},text:function(){var a=this.chart,b=this.args,e=this.style,g=this.attrs,j=this.group,v=this.bounds,l=this.options,n=this.getAbsoluteBounds(),z=p(l.align,j.options.textalign,"center").toLowerCase(),f=p(l.valign,j.options.textvalign,"middle").toLowerCase(),i=ta(p(l.text,l.label)),d=this.chart&&this.chart.renderer&&this.chart.renderer.smartLabel,s=p(l.wrap,j.options.wraptext)=="1",
c,D,m=p(l.rotatetext,j.options.rotatetext,"0").toLowerCase(),u=o.textRotationOptions[m],k=u!="0",m=k?"x":"y",k=k?"y":"x",a=a.options.orphanStyles,q=X({},a.defaultStyle.style||{}),F=a[j.id.toLowerCase()]||za,a=F.style.color,F=X(q,F.style),t=parseFloat(F.fontSize),q=u=="90"?-1:1,ca=p(l.font,j.options.font,F.fontFamily),j=r(l.fontsize,j.options.fontsize,t)*j.scaleText;s&&(c=r(l.wrapwidth,this.hasDimensionX?n.width/v.xs:void 0),D=r(l.wrapheight,this.hasDimensionY?n.height/v.ys:void 0),c&&(c*=v.xs),D&&
(D*=v.ys));e.fontFamily=ca;e.fontWeight=p(l.bold,l.isbold)=="1"?"bold":"normal";if(p(l.italic,l.isitalic)=="1")e.fontStyle="italic";if(l.bgcolor)e.backgroundColor=ra(l.bgcolor);if(l.bordercolor)e.borderColor=ra(l.bordercolor),e.border="1px solid "+e.borderColor;e.color=l.fontcolor?g.fill=ra(l.fontcolor):ra(a||g.fill.FCcolor.color);e.fontSize=j+"px";j==t?e.lineHeight=F.lineHeight:M(e);g.align=o.textAlignOptions[z]||"center";g.rotation=parseInt(u,10);d.setStyle(e);e=d.getSmartText(i,c,D,!1);switch(o.textVerticalAlignOptions[f]||
"middle"){case "top":n[m]+=(j-e.height)*q;break;case "bottom":n[m]+=j*q;break;default:n[m]+=(j-e.height*0.5)*q}g.align==="left"?n[k]+=r(l.leftmargin,0):g.align==="center"&&(n[k]+=r(l.leftmargin,0)*0.5);b[0]=e.text;b[1]=n.x;b[2]=n.y;delete g.stroke;delete g["stroke-weight"];return"text"},image:function(){var a=this,b=a.chart,e=a.style,g=b.chartWidth,j=b.chartHeight,b=a.options,n=a.attrs,l=a.args,o=xa(b.url),z=a.group.scaleImageX*p(Number(b.xscale),100)/100,f=a.group.scaleImageY*p(Number(b.yscale),
100)/100,i=a.getAbsoluteBounds(),d={width:1,height:1},s;if(!o)return l[0]=i.x,l[1]=i.y,l[2]=i.width,l[3]=i.height,l[4]=i.r,"rect";s=new Image;s.onload=function(){d=S("none","top","left",100,0,g,j,s);delete d.x;delete d.y;d=X(d,{width:(a.hasDimensionX?i.unscaled.width:d.width)*z,height:(a.hasDimensionY?i.unscaled.height:d.height)*f});setTimeout(function(){var c,f;if(c=a.wrapper)c.attr(d),(f=a.tracker)&&f.attr(c.getBBox()),c.css({opacity:e.opacity=ha(r(a.fillAlpha,a.borderAlpha),a.borderAlpha)/100});
a.onload&&a.onload(d)},0)};s.src=o;l[0]=o;l[1]=i.x;l[2]=i.y;l[3]=(a.hasDimensionX?i.unscaled.width:d.width)*z;l[4]=(a.hasDimensionY?i.unscaled.height:d.height)*f;e.opacity=ha(r(a.fillAlpha,a.borderAlpha),a.borderAlpha)/100;delete n.stroke;delete n.fill;delete n["stroke-linecap"];return"image"}};n.Highcharts.Chart.prototype.callbacks.unshift(function(a,b){var e=b.chartInstance,g=e.__state,j=b.dataObj||{},n=j.annotations,l=b.hcJSON,o={},z,f;if(!b.drawAnnotations||!e.dataReady()||!j.chart||!(j.chart.showannotations!=
"0"&&n&&n.groups&&n.groups.length)){if(!l||!l.annotations)return;n=l.annotations;if(n.options)o=n.options}else delete n.id;if(!g.annotationStores)g.annotationStores=[];g.annotationStores.push(e=n.id||"annotations");e=a[e]=[];o=X({showbelow:p(n.showbelow,n.showbelowchart),autoscale:n.autoscale,scaletext:n.scaletext,scaleimages:n.scaleimages,constrainedscale:n.constrainedscale,origw:p(n.origw,j.chart.origw,a.chartWidth),origh:p(n.origh,j.chart.origh,a.chartHeight),xshift:n.xshift,yshift:n.yshift,grpxshift:n.grpxshift,
grpyshift:n.grpyshift,xscale:n.xscale,yscale:n.yscale,rootxscale:r(n.xscale,100)/100,rootyscale:r(n.yscale,100)/100},o);if(b.snapLiterals){z=b.snapLiterals;j={};for(f in z)j["$"+f]=j["+$"+f]=z[f],j["-$"+f]=z[f]*-1;z=j}for(j=0;j<n.groups.length;j+=1)e.push(f=(new Q(n.groups[j],o,a,z)).draw()),f.id&&g.annotationGroupsById&&!a.renderer.forExport&&(g.annotationGroupsById[f.id]&&g.annotationGroupsById[f.id].destroy(),g.annotationGroupsById[f.id]=f)});aa.addEventListener("rendered",function(a,b){if(b.renderer===
"javascript"){var e=a.sender,g=e.jsVars||{},n=g.instanceAPI;if(!g.hcObj||!n||!n.drawAnnotations)delete e.showAnnotation,delete e.hideAnnotation;else{if(!e.showAnnotation)e.showAnnotation=e.ref.showAnnotation=j;if(!e.hideAnnotation)e.hideAnnotation=e.ref.hideAnnotation=G}}});aa.addEventListener("Initialized",function(a){var a=a.sender,b=a.__state;if(a.options.renderer==="javascript")b.annotationGroupsById={}});aa.addEventListener("Disposed",function(a){if(a.sender.options.renderer==="javascript"){var b=
a.sender,a=b.__state,b=b.jsVars.hcObj,e,g,j,n;for(n=a.annotationStores&&a.annotationStores.length||0;n--;){j=a.annotationStores[n];if(e=b&&b[j])for(;g=e.shift();)g.destroy();delete a[j]}}})}]);
FusionCharts(["private","modules.renderer.highcharts-maps",function(){var aa=this,n=aa.hcLib,$=n.chartAPI,Y=document,b=n.pluck,I=n.imprint,z=n.extend2,g=n.pluckNumber,sa=n.pluckFontSize,ea=n.placeLegendBlockRight,va=n.placeGLegendBlockRight,ha=n.placeGLegendBlockBottom,wa=n.placeLegendBlockBottom,qa=n.HCstub,ba=z(n.defaultPaletteOptions,{foregroundcolor:"333333",foregroundalpha:"100",foregrounddarkcolor:"111111",foregrounddarkalpha:"100",foregroundlightcolor:"666666",foregroundlightalpha:"100",backgroundlightcolor:"FFFFFF",
backgroundlightalpha:"100",backgroundlightangle:90,backgroundlightratio:"",backgroundcolor:"FFFFCC",backgroundalpha:"100",backgrounddarkcolor:"ffcc66",backgrounddarkalpha:"100",backgrounddarkangle:270,backgrounddarkratio:"",shadow:1}),V=n.setLineHeight,X=n.getValidValue,p=n.parseUnsafeString,r=n.getFirstColor,la=n.graphics.convertColor,fa=n.Highcharts,xa=fa.extend,ta=fa.isIE,S=fa.hasTouch,ra=fa.isWebKit,M=fa.hasSVG,za=fa.seriesTypes,na=n.FC_CONFIG_STRING,ya="rgba(192,192,192,"+(M?1.0E-6:0.0020)+")",
T=Y.documentMode===8?"visible":"",j=Math,G=j.min,Q=j.max,o=j.ceil,a=function(a,b){return b?xa(a.FCcolor,b):{FCcolor:a}},h=function(a){return a&&a.replace(/^#?([a-f0-9]+)/ig,"#$1")||"none"},e=function(){return{point:this}},U=function(a,b){var d,e;this.index=b;for(e in a)d=ba[a[e]],this[e]=d instanceof Array?d[b]:d},oa={right:function(a,b){return b},left:function(a,b){return a-b},center:function(a,b){return G(b,a-b)*2}},v={top:function(a,b){return b},middle:function(a,b){return G(b,a-b)*2},bottom:function(a,
b){return a-b}},l=function(a,b,d){function e(){var a=this.entityPathMap,c=this.data,f=c&&c.length||0,d=this.items,k=b.options.instanceAPI,m;if(b.options.chart.emulateFlashGutter){var k={startX:0,startY:0,endY:k.baseHeight*k._scaleFactor,endX:k.baseWidth*k._scaleFactor},g=this.group;this.chartObj.renderer.path(["M",k.startX,k.startY,"L",k.endX,k.endY]).add(g).attr({"stroke-width":1,stroke:la("FFFFFF","0")})}for(;f--;)m=c[f],k=m.id&&m.id.toLowerCase(),delete m.outlines,delete m.label,delete m.shortlabel,
delete m.labelposition,delete m.labelalignment,delete m.labelconnectors,k!==void 0&&k!==""&&(d[k]=new Z(I(m,a[k]),this.chartObj,k,this.group));for(m in a)d[m]||(d[m]=new Z(a[m],b,m,this.group))}function c(){var a=this.items,c=[],b,f;j.push({id:"entityLabels",items:c});for(f in a)(b=a[f].getLabelObject())&&c.push(b)}var g=b.options.instanceAPI,m=g.getEntityPaths(),u=g.hcJSON,k=g._scaleFactor,q=b.options[na],h=q._captionBlock,h=/bottom/.test(h.position)?0:h.height,j;q._labelBaseWidth=g.baseWidth+2*
b.plotLeft/k;q._labelBaseHeight=g.baseHeight+(2*b.plotTop-h)/k;q._labelXOffset=b.plotLeft/k;q._labelYOffset=(b.plotTop-h)/k;if(m&&b){if(!u.annotations)u.annotations={id:"geo",showbelow:0,autoscale:0,grpxshift:b.plotLeft?b.plotLeft:0,grpyshift:b.plotTop?b.plotTop:0,xscale:(g._scaleFactor?g._scaleFactor:1)*100,yscale:(g._scaleFactor?g._scaleFactor:1)*100,options:{useTracker:!0},groups:[]};j=u.annotations.groups;this.entityPathMap=m;this.data=a;this.chartObj=b;this.items={};this.group=d||b.seriesGroup;
e.call(this);c.call(this);this.drawLabels=c;this.drawTrackers=function(){var a=this.items,c;for(c in a)a[c].drawTracker()};this.destroy=function(){var a=this.items,c;for(c in a)a[c].destroy();delete this.entityPathMap;delete this.data;delete this.chartObj;delete this.items;delete this.group};this.init=e}},Z=function(f,i,d,h){function c(){var a=this.chart.renderer,c=this.options.outlines,b=this.group,f,d;for(f=c&&c.length||0;f--;)d=c[f],this.svgElems[f]={},this.svgElems[f].graphic=a.path(d).scale(Y).add(b).attr(B).shadow(Z,
ha,L);return this}function D(){}function m(){if(i.hoverPoint)n.raiseEvent.apply(n,i.hoverEntityEventArgs),delete i.hoverEntityEventArgs,i.hoverEntity&&i.hoverEntityAttr&&i.hoverEntity.attr(i.hoverEntityAttr),delete i.hoverEntity,delete i.hoverEntityAttr,i.hoverPoint=null}if(f&&i&&d!==void 0){this.chart=i;this.options=f;this.group=h;this.id=d;this.originalId=f.origId;this.isVisible=!0;this.svgElems={};this.connectorElem={};var u=i.options,k=u.instanceAPI,q=i.renderer,d=u.entities,l=d.dataLabels.style,
t=d.valuesForMarkers?null:f.cleanValue,ca=t===null?void 0:t,r=b(f.displayvalue,d.includeNameInLabels?d.useShortName?f.shortLabel:f.label:""),t=this.formattedValue=f.formattedValue||"",z=d.labelSepChar,x=g(f.showtooltip,d.showTooltip),A=this.toolText=x?p(b(f.tooltext,(d.useSNameInTooltip?f.shortLabel:f.label)+(isNaN(ca)?"":d.tooltipSepChar+t))):"",K,y,w,G=g(f.showlabel,d.showLabels),I=b(f.bordercolor,d.borderColor),C=b(f.borderalpha,d.borderAlpha);K=d.scaleBorder===1;var H=g(f.borderthickness,d.borderThickness),
U=b(f.labelconnectorcolor,d.connectorColor),X=b(f.labelconnectoralpha,d.connectorAlpha),V=b(f.font,l.fontFamily),E=g(parseInt(f.fontsize,10),parseInt(l.fontSize,10)),R=b(f.fontcolor,l.color),ia=g(f.labelpadding,d.labelPadding),$=d.hoverOnEmpty,ea=g(f.usehovercolor,$?d.useHoverColor:isNaN(ca)?0:d.useHoverColor),fa=g(f.hoverborderthickness,d.hoverBorderThickness),ma=g(f.fontbold,0),N=f.link,Z=d.shadow,ha=h.shadowGroup,l=!ta||M,Y=k._scaleFactor/d.baseScaleFactor;y=k._strokeWidth;var ba=(l?d.baseScaleFactor:
1)*y,ua=d.hiddenEntityFillObject||(d.hiddenEntityFillObject={fill:a({color:d.hiddenEntityColor,alpha:d.hiddenEntityAlpha})}),B,L,u=u[na],ka=u._labelBaseWidth,da=u._labelBaseHeight,ga=u._labelXOffset,O=u._labelYOffset;l?(H=K?H*ba:H/Y)&&ra&&(H=o(H)):H=K?H*y:H;fa=fa===void 0?H:K?H*ba:fa/Y;if(b(f.color,f.alpha,f.angle,f.ratio)!==void 0)u=b(f.color,d.fillColor),K=b(f.alpha,d.fillAlpha),l=b(f.angle,d.fillAngle),y=b(f.ratio,d.fillRatio),w=a({color:u,alpha:K,angle:l,ratio:y});else{if(!d.fillColorObject)d.fillColorObject=
a({color:b(d.fillColor),alpha:b(d.fillAlpha),angle:b(d.fillAngle),ratio:b(d.fillRatio)});if(!d.emptyColorObject)d.emptyColorObject=a({color:b(d.emptyEntityColor),alpha:b(d.emptyEntityAlpha),angle:b(d.emptyEntityAngle),ratio:b(d.emptyEntityRatio)});w=isNaN(ca)?d.emptyColorObject:d.fillColorObject;u=w.FCcolor.color;K=w.FCcolor.alpha;l=w.FCcolor.angle;y=w.FCcolor.ratio}A===""&&(x=0);B={stroke:la(I,C),"stroke-width":H,fill:this.fillColor=w};I=K.split(",");if(Z&&!ha)ha=h.shadowGroup=q.g("shadow-group").add(h);
H&&I.push(C);L={opacity:Q.apply(j,I)/100};if(ea){if(b(f.hovercolor,f.hoveralpha,f.hoverangle,f.hoverratio)!==void 0)u=b(f.hoverfillcolor,f.hovercolor,d.hoverFillColor),K=b(f.hoverfillalpha,f.hoveralpha,d.hoverFillAlpha),l=b(f.hoverfillangle,f.hoverangle,d.hoverFillAngle),y=b(f.hoverfillratio,f.hoverratio,d.hoverFillRatio),h=a({color:u,alpha:K,angle:l,ratio:y});else{if(!d.hoverColorObject)d.hoverColorObject=a({color:d.hoverFillColor,alpha:d.hoverFillAlpha,angle:d.hoverFillAngle,ratio:d.hoverFillRatio});
h=d.hoverColorObject}this.hoverColor=h}!f.displayvalue&&d.includeValueInLabels&&!isNaN(ca)&&(r=r===void 0?t:r+z+t);this.value=ca;this.addMouseGestures=function(){var a=this,c=a.options,f=a.svgElems,b,d,g=x&&i.tooltip,q={"stroke-width":fa,fill:a.hoverColor},h={"stroke-width":H,fill:a.fillColor},u={value:a.value,label:c.label,shortLabel:c.shortLabel,originalId:a.originalId||a.id,id:a.id},s={value:a.value,lName:c.label,sName:c.shortLabel,id:a.originalId||a.id};if(!isNaN(ca)||$)for(b in f)c=k._translateX?
k._translateX:0,d=k._translateY?k._translateY:0,c=f[b].pointProxy={tooltipPos:[c,d],series:{},_fmEntity:a,svgElm:f[b].tracker.svgElm,tracker:f[b].tracker,toolText:A,getLabelConfig:e,onMouseOut:m,firePointEvent:D,onClick:function(a){aa.raiseEvent("entityclicked",u,k.chartInstance,a);N!==void 0&&k.linkClickFN.call({link:N})}},N!==void 0&&f[b].tracker.css({cursor:"pointer",_cursor:"hand"}),f[b].tracker.on("click",c.onClick).on(S?"touchstart":"mouseover",function(c){var f=a.chart,b=f.plotLeft,d=f.plotTop,
i;return function(e){m();if(e.type==="touchstart"){c.onClick.apply(this,arguments)}if(g){ta?(c.tooltipPos[0]=(e.layerX||e.x||e.clientX||e.offsetX||e.originalEvent&&e.originalEvent.layerX)-b+20,c.tooltipPos[1]=(e.layerY||e.y||e.clientY||e.offsetY||e.originalEvent&&e.originalEvent.layerY)-d-15):(c.tooltipPos[0]=(e.layerX||e.x||e.offsetX||e.clientX||e.originalEvent&&e.originalEvent.layerX)-b+20,c.tooltipPos[1]=(e.layerY||e.y||e.offsetY||e.clientY||e.originalEvent&&e.originalEvent.layerY)-d-15);if(S&&(c.tooltipPos[0]<=0||c.tooltipPos[1]<=0))i=i||c.tracker.getBBox(),
c.tooltipPos[0]=i.x*Y,c.tooltipPos[1]=i.y*Y;g.refresh(c,!1)}f.hoverPoint=c;f.hoverEntityEventArgs=["entityrollout",u,k.chartInstance,[k.chartInstance.id,"rollOut",s],e];if(ea&&a.isVisible)f.hoverEntity=c._fmEntity,f.hoverEntityAttr=h,a.attr(q);n.raiseEvent("entityrollover",u,k.chartInstance,[k.chartInstance.id,"rollOver",s],e)}}(c))};this.attr=function(a,c){var f=this.svgElems,b;for(b in f)f[b].graphic&&f[b].graphic.attr(a,c)};this.draw=c;this.getLabelObject=function(){var a=this,c=a.options,f=a.chart.renderer,
b=c.labelPosition,d=c.labelAlignment,i=c.labelConnectors,e=a.svgElems[0]&&a.svgElems[0].graphic,m,g;if(!G||!e||!r)return null;for(m=c=i&&i.length||0;m--;)g=i[m],a.connectorElem[m]=f.path(g).scale(Y).add(a.group).attr({stroke:la(U,X),"stroke-width":ba});b?(f=b[0],i=b[1]):(b=e.getBBox(),f=b.x+b.width/2,i=b.y+b.height/2);d?(b=d[0],d=d[1],b==="right"?f-=ia:b==="left"&&(f+=ia),d==="top"?i-=ia:d==="bottom"&&(i+=ia)):(b="center",d="middle");return{x:f.toString(),y:i.toString(),wrapwidth:oa[b](ka,f+ga)-ia,
wrapheight:v[d](da,i+O)-ia,wrap:1,type:"text",align:b,valign:d,text:r,link:c?N:null,bgcolor:"",bordercolor:"",fontcolor:R,fontsize:parseFloat(E)/k._scaleFactor,font:V,bold:ma,onclick:function(){return a.svgElems[0].pointProxy.onClick.apply(this,arguments)},onmouseover:function(){var c=a.svgElems[0],c=c&&c.tracker.element[S?"ontouchstart":"onmouseover"],b=arguments[0],f=b.data;if(M)b.layerX=f.args&&f.args[1],b.layerY=f.args&&f.args[2];return c&&c.apply(this,arguments)}}};this.translate=function(a,
c){var b=this.svgElems,f;if(typeof a===OBJECTSTRING&&a!==null)c=a.y,a=a.x;for(f in b)b[f].graphic.translate(a,c),b[f].tracker.translate(a,c)};this.destroy=function(){var a=this.svgElems,c=this.connectorElem,b;for(b in a)a[b].destroy&&a[b].destroy();for(b in c)c[b].destroy&&c[b].destroy();delete this.value;delete this.formattedValue;delete this.toolText;delete this.fillColor;delete this.hoverColor;delete this.chart;delete this.group;delete this.id;delete this.isVisible;delete this.svgElems;delete this.connectorElem;
delete this.renderer;delete this.options};this.drawTracker=function(){var a=this.chart,c=a.renderer,b=this.options.outlines,f,d;for(f=b&&b.length||0;f--;)d=b[f],this.svgElems[f].tracker=c.path(d).scale(Y).add(a.trackerGroup).attr({isTracker:!0,stroke:"none",fill:ya,"stroke-width":1,visibility:T});this.addMouseGestures();return this};this.show=function(){var a=this.svgElems,c;this.isVisible=!0;for(c in a)a[c].graphic&&a[c].graphic.attr(B)};this.hide=function(){var a=this.svgElems,c;this.isVisible=
!1;for(c in a)a[c].graphic&&a[c].graphic.attr(ua)};c.call(this);d.hideEmptyEntities&&ca===void 0&&this.hide()}},Ka=function(f,i){this.markerObjs={};this.shapeObjs={};this.markerElemObj={};this.connectors=[];this.options=f;this.chart=i;this.group=i.renderer.g("markers").add(i.seriesGroup);var d=i&&i.options&&i.options.instanceAPI,e=d.hcJSON,c={top:function(a,c,b){return{x:a.toString(),y:(c-b).toString(),align:"center",valign:"top"}},left:function(a,c,b){return{x:(a-b).toString(),y:c.toString(),align:"right",
valign:"middle"}},right:function(a,c,b){return{x:(a+b).toString(),y:c.toString(),align:"left",valign:"middle"}},bottom:function(a,c,b){return{x:a.toString(),y:(c+b).toString(),align:"center",valign:"bottom"}},center:function(a,c){return{x:a.toString(),y:c.toString(),align:"center",valign:"middle"}}},h;if(!e.annotations)e.annotations={id:"geo",showbelow:0,autoscale:0,grpxshift:i.plotLeft?i.plotLeft:0,grpyshift:i.plotTop?i.plotTop:0,xscale:(d._scaleFactor?d._scaleFactor:1)*100,yscale:(d._scaleFactor?
d._scaleFactor:1)*100,options:{useTracker:!0},groups:[]};h=e.annotations.groups;this.applyMarkers=function(){var a=this.chart,c=a.plotLeft,f=a.plotTop,d=a.options,a=d[na],i=d.instanceAPI,d=d.markers,e=this.markerObjs,s=this.shapeObjs,j=this.options.application,l=d.dataLabels.style.fontFamily,n=d.dataLabels.style.fontSize,r=d.dataLabels.style.fontColor,p=d.showTooltip,y=d.showLabels,w=d.labelPadding,o=d.labelWrapWidth,v=d.labelWrapHeight,C=d.labelSepChar,H=d.tooltipSepChar,I=d.fillColor,Q=d.fillAlpha,
M=d.fillRatio,E=d.fillAngle,R=d.startAngle,U=d.borderThickness,S=d.borderColor,T=d.borderAlpha,X=d.radius,V=d.autoScale?i._scaleFactor:1,N=j&&j.length,Y=[],$=[],ea=function(a){var c;if(a=s[a]){if(a.type==="polygon")a.sides<3?a.type="circle":a.startangle=R;else if(a.type==="arc")c=a.radius&&a.radius*V||X,a.radius=c,a.innerradius=a.innerradius&&a.innerradius*V||c*0.6;return a}else return null},fa={right:function(a,c){return c},left:function(a,c){return a-c},center:function(a,c){return G(c,a-c)*2}},
ha={top:function(a,c){return c},middle:function(a,c){return G(c,a-c)*2},bottom:function(a,c){return a-c}},B,L,ka,da,ga,O,W,Z;h.push({id:"markers",fillalpha:"100",items:Y});for(h.push({id:"markerlabels",items:$});N;N-=1)if(B=j[N-1],O=e[B.id&&B.id.toLowerCase()],O!==void 0){this.markerElemObj[B.id.toLowerCase()]=B;B._annotationIndex=Y.length;W=b(B.shapeid,O.shapeid,"circle").toLowerCase();L=parseFloat(B.scale);ka=b(B.label,O.label,"");ga=b(B.labelpos,O.labelpos,"top");isNaN(L)?L=1:L<0?L=0:L>5&&(L=5);
Z=B.formattedValue===void 0?"":B.formattedValue;ka=ka||"";da=Z?ka+H+Z:ka;ka=Z?ka+C+Z:ka;L=g(B.radius,O.radius,X)*L*V||1.0E-4;B={x:O.x.toString(),y:O.y.toString(),fillcolor:b(B.fillcolor,B.color,I),fillalpha:b(B.fillalpha,B.alpha,Q),fillratio:b(B.fillratio,M),fillangle:b(B.fillangle,E),borderthickness:g(B.borderthickness,U),bordercolor:b(B.bordercolor,S),borderalpha:b(B.borderalpha,T),radius:L,tooltext:p?B.tooltext?B.tooltext:da:"",link:B.link,showshadow:g(B.showshadow,d.shadow),_markerLabel:ka,_markerId:O.id,
onmouseover:function(a){var b=a.data,d=b.options,b=b.bounds,e=d._markerRollOverArgs;if(!e)e=d._markerRollOverArgs={x:b.x1/b.xs,y:b.y1/b.ys,scaledX:b.x1,scaledY:b.y1,chartX:c+b.x1,chartY:f+b.y1,id:d._markerId,label:d._markerLabel};aa.raiseEvent("markerrollover",e,i.chartInstance,a)},onmouseout:function(a){aa.raiseEvent("markerrollout",a.data.options._markerRollOverArgs,i.chartInstance,a)},onclick:function(a){aa.raiseEvent("markerclicked",a.data.options._markerRollOverArgs,i.chartInstance,a)}};W===
"triangle"?z(B,{type:"polygon",sides:3,startangle:R}):W==="diamond"?z(B,{type:"polygon",sides:4,startangle:R}):W==="arc"?z(B,{type:"arc",startangle:0,endangle:360,innerradius:L*0.6}):W==="circle"?B.type="circle":z(B,ea(W));if(B.type==="image")B.onload=function(a){var c=this.options,b=a.width,a=a.height,f=(Number(c.x)-b/(2*i._scaleFactor))*i._scaleFactor,c=(Number(c.y)-a/(2*i._scaleFactor))*i._scaleFactor,d;if(b&&a)for(d in{wrapper:1,tracker:1})this[d]&&this[d].attr({x:f,y:c,width:b,height:a})};Y.push(B);
if(y){W=B.labelpadding||w;ga=this.getLabelAttrs(ga,W,B);da=ga.align;O=ga.valign;var ba=a._labelBaseWidth;L=a._labelBaseHeight;var la=a._labelXOffset;Z=a._labelYOffset;ba=o?o:fa[da](ba,Number(ga.x)+la);O=v?v:ha[O](L,Number(ga.y)+Z);L=i._scaleFactor;ba>W&&(ba-=W);O>W&&(O-=W);$.push(z({type:"text"},{text:ka,tooltext:B.tooltext,x:ga.x,y:ga.y,align:da,valign:ga.valign,wrap:1,wrapwidth:ba,wrapheight:O,fontsize:n/L,font:l,fontcolor:r}))}}};this.defineMarkersNShapes=function(){var a=this.options.definition,
c=this.options.shapes,b=a.length,f,d;if(a&&a.length){for(;b;b-=1)if(f=a[b-1],d=f.id.toLowerCase())this.markerObjs[d]=f;if(c&&c.length)for(b=c.length;b;b-=1)if(f=c[b-1],d=f.id.toLowerCase())this.shapeObjs[d]=f}};this.getConnectorJSON=function(a){var c=i.options.connectors,f=a.to,e=this.markerObjs[a.from.toLowerCase()],f=this.markerObjs[f.toLowerCase()],h=a.link,s=a.label,j=g(a.showtooltip,c.showTooltip),l=j?a.tooltext:"",n=b(a.thickness,c.thickness),D=b(a.color,c.color),r=b(a.alpha,c.alpha),p=b(a.dashed,
c.dashed),o=g(a.dashlen,c.dashLen),a=g(a.dashgap,c.dashGap),w;return!e||!f?null:(w={fromMarkerId:e.id,toMarkerId:f.id},{x:e.x,y:e.y,tox:f.x,toy:f.y,dashed:p,dashlen:o,dashgap:a,link:h,tooltext:j?l:"",thickness:n,color:D,alpha:r,label:s,showshadow:c.shadow,onmouseover:function(a){aa.raiseEvent("connectorrollover",w,d.chartInstance,a)},onmouseout:function(a){aa.raiseEvent("connectorrollout",w,d.chartInstance,a)},onclick:function(a){aa.raiseEvent("connectorclicked",w,d.chartInstance,a)}})};this.drawConnectors=
function(){var a=i.options.connectors,c=a.showLabels,b=this.options.connectors,f=b&&b.length,e=[],g=[],s;if(f){h.push({id:"connectors",fillalpha:"100",items:e});for(h.push({id:"connectorLabels",fillalpha:"100",items:g});f--;)if(s=b[f],s=this.getConnectorJSON(s))e.push(z({type:"line"},s)),s.label&&c&&g.push(z({type:"text"},{x:((Number(s.x)+Number(s.tox))/2).toString(),y:((Number(s.y)+Number(s.toy))/2).toString(),text:s.label,align:"center",valign:"middle",font:a.font,fontsize:a.fontSize/d._scaleFactor,
fontcolor:a.fontColor,bgcolor:a.labelBgColor,bordercolor:a.labelBorderColor,tooltext:s.showtooltip?s.tooltext:""}))}};this.getLabelAttrs=function(a,b,f,i,e){var g,h=a&&a.toLowerCase();c[h]||(h="center");a=Number(f.x);g=Number(f.y);f=i===void 0||e===void 0?f.radius||0:/^(top|bottom)$/ig.test(h)&&e*0.5||/^(left|right)$/ig.test(h)&&i*0.5||0;f=(Number(f)+Number(b))/d._scaleFactor;return c[h](a,g,f)};this.setMarkerVisibility=function(c,b){var f=this.chart,f=f.options&&f.options.instanceAPI&&f.options.instanceAPI.chartInstance;
if(f=(f.__state&&f.__state.annotationGroupsById).markers.items[b._annotationIndex]){if(!b._origFill)b._origFill=a({alpha:f.fillAlpha,color:f.fillColor,angle:f.fillAngle,ratio:f.fillRatio}),b._hideFill=a({alpha:"0",color:f.fillColor,angle:f.fillAngle,ratio:f.fillRatio});c?f.wrapper.attr({fill:b._origFill}):f.wrapper.attr({fill:b._hideFill})}};this.destroy=function(){delete this.markerObjs;delete this.shapeObjs;delete this.markerElemObj;delete this.connectors;delete this.options;delete this.chart;this.group.destroy();
delete this.group};this.defineMarkersNShapes();this.drawConnectors();this.applyMarkers()};xa(n.eventList,{entityrollover:"FC_Event",entityrollout:"FC_Event"});$("geo",{name:"(unknown)",revision:1,creditLabel:!1,standaloneInit:!1,charttopmargin:10,chartrightmargin:10,chartbottommargin:10,chartleftmargin:10,baseWidth:400,baseHeight:300,baseScaleFactor:1,defaultSeriesType:"geo",entities:{},chart:function(f,i){z(this.dataObj.chart,{charttopmargin:this.dataObj.chart.maptopmargin,chartrightmargin:this.dataObj.chart.maprightmargin,
chartbottommargin:this.dataObj.chart.mapbottommargin,chartleftmargin:this.dataObj.chart.mapleftmargin,animation:this.dataObj.chart.animation||"0"});var d=this.dataObj,e=qa(d,f,i,this),c=d.chart,j=e.chart,m=m=e[na],l=j.useRoundEdges=g(c.useroundedges)===1,k=l?1:0,l=l?0:1,q=j.use3DLighting=g(c.use3dlighting,1)===1,n=z({},e.tooltip.style),t=new U(this.colorPaletteMap,(c.palette>0&&c.palette<6?c.palette:g(this.paletteIndex,1))-1),o=b(c.basefont,"Verdana"),pa=sa(c.basefontsize,10),v=b(c.basefontcolor,
t.basefontcolor),x=sa(c.outcnvbasefontsize,pa),A=b(c.outcnvbasefont,o),K=x+"px",y=h(b(c.outcnvbasefontcolor,v)),w=b(c.bgcolor,c.canvasbgcolor,t.canvasbgcolor),G=b(c.bgalpha,c.canvasbgalpha,t.canvasbgalpha),I,C;pa+="px";v=h(v);this.realtimeEnabled&&this.postHCJSONCreation&&this.postHCJSONCreation.call(this,e);j.events.click=this.linkClickFN;m.numberFormatter=this.numberFormatter;z(m,{width:f,height:i,showTooltip:g(c.showtooltip,this.showtooltip,1),tooltipSepChar:b(c.tooltipsepchar,", "),showValues:g(c.showvalues,
this.showValues,1),showCanvasBG:b(c.showcanvasbg,1),useValuesForMarkers:g(c.usevaluesformarkers,0),outCanvasStyle:{fontFamily:A,color:y,fontSize:K},inCanvasStyle:{fontFamily:o,fontSize:pa,color:v}});I=V(m.outCanvasStyle);C=V(m.inCanvasStyle);m.trendStyle=m.outCanvasStyle;m.showCanvasBG=="0"&&(G="0");var H=b(c.bordercolor,t.plotbordercolor),M=b(c.fillcolor,t.plotfillcolor),S=b(c.fillalpha,t.plotfillalpha),T=b(c.fillratio,t.plotfillratio),E=b(c.fillangle,t.plotfillangle),R=b(c.emptyentityfillcolor,
c.emptyentitycolor,M);z(e,{chart:{emulateFlashGutter:g(c._emulateflashgutter,1)},title:{text:p(c.caption),offsetX:Number(c.captionxshift),offsetY:Number(c.captionyshift),position:b(c.captionposition,c.captionxshift!==void 0||c.captionyshift!==void 0?"top left":"top"),padding:g(c.captionpadding,10),style:{fontFamily:A,color:y,fontSize:x+3+"px",fontWeight:g(c.captionfontbold)===0?"normal":"bold"}},subtitle:{text:p(c.subcaption),style:{fontFamily:A,color:y,fontSize:x+1+"px",fontWeight:g(c.subcaptionfontbold)===
0?"normal":"bold"}},orphanStyles:{defaultStyle:{style:z({},m.inCanvasStyle)}},tooltip:{enabled:m.showTooltip!==0,style:{fontFamily:o,fontSize:pa,lineHeight:C,color:v,padding:g(c.tooltippadding,this.tooltippadding,4),backgroundColor:void 0,borderColor:void 0,border:void 0},backgroundColor:la(b(n.backgroundColor,c.tooltipbgcolor,t.tooltipbgcolor),b(c.tooltipbgalpha,"100")),borderColor:la(b(n.borderColor,c.tooltipbordercolor,t.tooltipbordercolor),b(c.tooltipborderalpha,"100")),borderWidth:g(c.tooltipborderthickness,
l),borderRadius:g(c.tooltipborderradius,k+1),shadow:g(c.showtooltipshadow,k)?{enabled:!0,opacity:g(Q(c.tooltipbgalpha,c.tooltipborderalpha),100)/100}:!1},legend:{itemStyle:{fontFamily:A,fontSize:K,lineHeight:I,color:y},itemHiddenStyle:{fontFamily:A,fontSize:K,lineHeight:I},enabled:g(c.showlegend,1),title:{text:p(c.legendcaption),style:{fontFamily:A,fontSize:K,lineHeight:I,color:y}},position:b(c.legendposition,g(d.colorrange&&d.colorrange.gradient,0)===0?"right":"bottom"),backgroundColor:b(c.legendbgcolor,
t.bgcolor),backgroundAlpha:b(c.legendbgalpha,"100"),borderColor:b(c.legendbordercolor,t.legendbordercolor),borderThickness:b(c.legendborderthickness,"1"),borderAlpha:b(c.legendborderalpha,"100"),shadow:g(c.legendshadow,1),allowDrag:g(c.legendallowdrag,0),scroll:{scrollBgColor:b(c.legendscrollbgcolor,"AAAAAA"),scrollBtnColor:b(c.legendscrollbtncolor,"BBBBBB"),scrollBarColor:b(c.legendscrollbarcolor,"CCCCCC")},reversed:g(c.reverselegend,0),interactive:g(c.interactivelegend,0),minColor:R,lighting3d:q},
markers:{dataLabels:{style:{fontFamily:b(c.markerfont,o),fontSize:g(c.markerfontsize,parseInt(pa,10)),fontColor:b(c.markerfontcolor,v)}},showTooltip:g(c.showmarkertooltip,m.showTooltip),showLabels:g(c.showmarkerlabels,c.showlabels,1),labelPadding:b(c.markerlabelpadding,"5"),labelWrapWidth:g(c.markerlabelwrapwidth,0),labelWrapHeight:g(c.markerlabelwrapheight,0),fillColor:b(c.markerfillcolor,c.markerbgcolor,t.markerbgcolor),fillAlpha:b(c.markerfillalpha,t.markerbgalpha),fillAngle:b(c.markerfillangle,
t.markerbgangle),fillRatio:b(c.markerfillratio,t.markerbgratio),fillPattern:b(c.markerfillpattern,t.markerbgpattern),borderThickness:b(c.markerborderthickness,1),borderColor:b(c.markerbordercolor,t.markerbordercolor),borderAlpha:g(c.markerborderalpha,t.markerborderalpha),radius:g(c.markerradius,7),labelSepChar:b(c.labelsepchar,", "),tooltipSepChar:m.tooltipSepChar,autoScale:g(c.autoscalemarkers,0),mapValueToRadius:g(c.mapmarkervaluetoradius,0),startAngle:g(c.markerstartangle,90),maxRadius:g(c.maxmarkerradius,
0.3*f),minRadius:g(c.minmarkerradius,0.02*f),applyAll:g(c.applyallmarkers,0),shadow:g(c.showmarkershadow,c.showshadow,0)},connectors:{thickness:g(c.connectorthickness,c.markerconnthickness,"2"),color:b(c.connectorcolor,c.markerconncolor,t.markerbordercolor),alpha:b(c.connectoralpha,c.markerconnalpha,"100"),dashed:g(c.connectordashed,c.markerconndashed,0),dashLen:g(c.connectordashlen,c.markerconndashlen,3),dashGap:g(c.connectordashgap,c.markerconndashgap,2),font:b(c.connectorfont,c.markerconnfont,
o),fontColor:b(c.connectorfontcolor,c.markerconnfontcolor,v),fontSize:g(c.connectorfontsize,c.markerconnfontsize,parseInt(pa,10)),showLabels:g(c.showconnectorlabels,c.showmarkerlabels,c.showlabels,1),labelBgColor:b(c.connectorlabelbgcolor,c.markerconnlabelbgcolor,t.plotfillcolor),labelBorderColor:b(c.connectorlabelbordercolor,c.markerconnlabelbordercolor,t.markerbordercolor),shadow:g(c.showconnectorshadow,c.showmarkershadow,c.showshadow,0),showTooltip:g(c.showconnectortooltip,c.showmarkertooltip,
m.showTooltip)},entities:{baseScaleFactor:this.baseScaleFactor,dataLabels:{style:{fontFamily:o,fontSize:pa,lineHeight:C,color:e.plotOptions.series.dataLabels.color=v}},fillColor:M,fillAlpha:S,fillRatio:T,fillAngle:E,borderColor:H,borderAlpha:b(c.borderalpha,this.borderAlpha,"100"),borderThickness:g(c.showborder,1)?g(c.borderthickness,1):0,scaleBorder:g(c.scaleborder,0),hoverFillColor:b(c.hoverfillcolor,c.hovercolor,t.plothoverfillcolor),hoverFillAlpha:b(c.hoverfillalpha,c.hoveralpha,t.plothoverfillalpha),
hoverFillRatio:b(c.hoverfillratio,c.hoverratio,t.plothoverfillratio),hoverFillAngle:b(c.hoverfillangle,c.hoverangle,t.plothoverfillangle),hoverBorderThickness:b(c.hoverborderthickness),emptyEntityColor:R,emptyEntityAlpha:b(c.emptyentityfillalpha,c.emptyentityalpha,S),emptyEntityRatio:b(c.emptyentityfillratio,c.emptyentityratio,T),emptyEntityAngle:b(c.emptyentityfillangle,c.emptyentityangle,E),connectorColor:b(c.labelconnectorcolor,c.connectorcolor,v),connectorAlpha:b(c.labelconnectoralpha,c.connectoralpha,
"100"),useHoverColor:g(c.usehovercolor,1),hoverOnEmpty:g(c.hoveronempty,1),labelPadding:g(c.labelpadding,5),showLabels:g(c.showlabels,1),includeNameInLabels:g(c.includenameinlabels,1),includeValueInLabels:g(c.includevalueinlabels,0),useSNameInTooltip:g(c.usesnameintooltip,0),useShortName:g(c.usesnameinlabels,1),labelSepChar:b(c.labelsepchar,", "),showTooltip:g(c.showentitytooltip,m.showTooltip),tooltipSepChar:m.tooltipSepChar,valuesForMarkers:g(c.usevaluesformarkers,0),hideEmptyEntities:g(c.hideemptyentities,
0),showHiddenEntityBorder:g(c.showhiddenentityborder,1),hiddenEntityColor:b(c.hiddenentitycolor,c.hiddenentityfillcolor,c.hiddenentityalpha||c.hiddenentityfillalpha?R:"ffffff"),hiddenEntityAlpha:b(c.hiddenentityalpha,c.hiddenentityfillalpha,0.0010),shadow:g(c.showshadow,this.defaultPlotShadow,t.shadow)},entitydef:{useSNameAsId:g(c.usesnameasid,0)}});if(c.tooltipcolor)e.tooltip.style.color=r(c.tooltipcolor);if(b(c.clickurl)!==void 0)j.link=c.clickurl,j.style.cursor="pointer",ta&&(j.style._cursor="hand"),
e.plotOptions.series.point.events.click=function(){j.events.click.call({link:c.clickurl})};e.plotOptions.series.allowPointSelect=!0;z(j,{defaultSeriesType:this.defaultSeriesType,paletteIndex:t.index,borderRadius:g(c.canvasborderradius,0),borderColor:la(b(c.canvasbordercolor,t.canvasbordercolor),b(c.canvasborderalpha,t.canvasborderalpha)),borderWidth:g(c.showcanvasborder,l)?g(c.canvasborderthickness,1):0,backgroundColor:a({color:w,alpha:G,angle:b(c.bgangle,c.canvasbgangle,t.canvasbgangle),ratio:b(c.bgratio,c.canvasbgratio,t.canvasbgratio)}),
plotBorderColor:"#ffffff",plotBorderWidth:0,plotBackgroundColor:a({color:"#ffffff",alpha:0}),bgSWF:b(c.bgimage,c.bgswf),bgSWFAlpha:g(c.bgimagealpha,c.bgswfalpha,100),bgImageScale:g(c.bgimagescale,100),bgImageDisplayMode:b(c.bgimagedisplaymode,"none").toLowerCase(),logoURL:X(c.logourl),logoPosition:b(c.logoposition,"tl").toLowerCase(),logoAlpha:g(c.logoalpha,100),logoLink:X(c.logolink),logoScale:g(c.logoscale,100),logoLeftMargin:g(c.logoleftmargin,0),logoTopMargin:g(c.logotopmargin,0)});m=j.bgImageDisplayMode;
k=X(c.bgimagevalign,"").toLowerCase();l=X(c.bgimagehalign,"").toLowerCase();m=="tile"||m=="fill"||m=="fit"?(k!="top"&&k!="middle"&&k!="bottom"&&(k="middle"),l!="left"&&l!="middle"&&l!="right"&&(l="middle")):(k!="top"&&k!="middle"&&k!="bottom"&&(k="top"),l!="left"&&l!="middle"&&l!="right"&&(l="left"));j.bgImageVAlign=k;j.bgImageHAlign=l;this.parseStyles(e);V(e.title.style);V(e.subtitle.style);V(e.tooltip.style);this.parseExportOptions(e);this.preSeriesAddition&&this.preSeriesAddition(e,d,f,i);this.series&&
this.series(d,e,this.name,f,i);this.postSeriesAddition&&this.postSeriesAddition(e,d,f,i);this.spaceManager(e,d,f,i);window.console&&window.FC_DEV_ENVIRONMENT&&window.console.log(e);return e},series:function(a,e){var d=this.numberFormatter,h=this.hcJSON.series,c=this.dataObj,j=e[na],m=c.colorrange,m=m&&m.color,l=e.legend,k=j.useValuesForMarkers?c.markers&&c.markers.application||[]:c.data,q={},r=function(a){for(var c,b,f=v&&v.length||0;f--;)if(c=v[f],b=Number(c.maxvalue),c=g(c.minvalue,e.colorRange.scaleMin),
a>=c&&a<=b)return f;return null},t=Infinity,p=-Infinity,o,v,x;l.type=c.colorrange&&c.colorrange.gradient==="1"?"gradient":"point";for(x=k&&k.length||0;x--;)o=k[x],value=o.value,o.cleanValue=d.getCleanValue(value),o.formattedValue=o.cleanValue!==null?d.dataLabels(value):void 0,o.origValue=value,o.cleanValue!==null&&(t=G(o.cleanValue,t),p=Q(o.cleanValue,p));t===Infinity&&(t=void 0);p===-Infinity&&(p=void 0);e.colorRange=new n.colorRange({colorRange:c.colorrange,dataMin:t,dataMax:p,defaultColor:l.minColor,
numberFormatter:d});x=(v=e.colorRange.colorArr)&&v.length||0;j._doNotShowLegend=!0;if(x>0){for(;x--;){o=v[x];if(j._doNotShowLegend&&(o.label!==""||o.label!==void 0))j._doNotShowLegend=!1;h.push({type:this.defaultSeriesType,showInLegend:!0,data:[],name:o.label,color:o.code,rangeMin:o.minvalue,rangeMax:o.maxvalue,allVisible:!0,allHidden:!1})}for(x=k&&k.length||0;x--;)if(o=k[x],d=r(g(o.value)),d!==null&&(j=l.type==="gradient"?e.colorRange.getColorObj(o.value).code:m&&m[d]&&b(m[d].color,m[d].code),q[d]||
(q[d]=[]),j))o.color=o.color?o.color:j,q[d].push(o);h=h.reverse();for(x in q)h[x]&&(h[x].data=q[x])}else h.push({type:this.defaultSeriesType,data:k||[]})},spaceManager:function(a,b,d,e){var c=a.chart,g=a[na];g.smartLabel=this.smartLabel;var h=c.spacingLeft,j=c.spacingTop,k=this.baseWidth,l=this.baseHeight;d-=c.spacingRight+h;var n=e-(c.spacingBottom+j),e=g._captionBlock=this.manageTitleSpace(a,b,o,n),a=g._legendBlock=this.placeLegendBlock(a,b,d,n-e.height,e.isBottom?e.height:0),o=d-a.width,a=n-e.height-
a.height,p,r;g.viewportWidth=o;g.viewportHeight=a;g.trackerTop=j;g.trackerLeft=h;o/a>k/l?(h=a/l,p=(o-h*k)/2,k=200/(l*h)):(h=o/k,r=(a-h*l)/2,k=200/(k*h));p=p?p:0;r=r?r:0;c.marginLeft+=p;c.marginRight+=p;c.marginTop+=r;c.marginBottom+=r;/bottom/i.test(e.position)||(r+=e.height,g.trackerTop+=e.height);this._scaleFactor=h;this._strokeWidth=k;this._translateX=p;this._translateY=r},placeLegendBlock:function(a,b,d,e,c){var g=a.legend,h=a[na],j=g.position.toLowerCase(),k={position:j};if(b.chart.showlegend===
"0"||h._doNotShowLegend)return k.height=0,k.width=0,k;if(j==="bottom"){if(k.height=g.type==="gradient"?ha(a,b,d,e):wa(a,b,d,e),k.width=0,c)g.y=-c}else d/=2,k.width=g.type==="gradient"?va(a,b,d,e):ea(a,b,d,e),k.height=0;return k},manageTitleSpace:function(a,b,d,e){var c=this.hcJSON,a=c.title,b=c.chart,c=c.subtitle,g=this.smartLabel,h=e/2,j=0,k=a.position.toLowerCase(),l=a.padding,n=!1,o=a.offsetX,p=a.offsetY,r=0,v={},x,A,z;if(a.text===""&&c.text==="")return{height:0,position:k};if(!isNaN(o)||!isNaN(p))n=
!0,o=isNaN(o)?0:o,p=isNaN(p)?0:p;x=a.text;if(x!==""){g.setStyle(a.style);A=g.getOriSize(x);if(A.width>d||A.height>h)A=g.getSmartText(x,d,h),a.text=A.text;r=A.height;j+=r}h-=j;x=c.text;if(x!==""){g.setStyle(c.style);A=g.getOriSize(x);if(A.width>d||A.height>h)A=g.getSmartText(x,d,h),c.text=A.text;j+=A.height}j+l>h?j=h:j+=l;/bottom/.test(k)?(d=e-j+l+g.getOriSize("Wqt").height,a.y=d,c.y=d+r,n?(a.y+=p,c.y+=p,a.x=o,c.x=o):(b.marginBottom+=j,v.isBottom=!0)):n?(a.y=p,c.y=p+r,a.x=o,c.x=o):b.marginTop+=j;a.align=
c.align=(z=k.match(/left|right/))&&z[0]||"center";v.height=n?0:j;v.position=k;return v},getEntityPaths:function(){return this.entities},redefineEntities:function(a,b){var d=this.entities,e={},c={},g,h,j,k,l,n,o,p;for(o=a.length;o--;)if(g=a[o],h=g.internalid,l=g.newid?g.newid:h,j=g.sname,g=g.lname,(k=d[h])&&!(l!==h&&d[l])){e[l]=l={origId:h};c[h]=!0;for(n in k)l[n]=k[n];l.shortLabel=j?j:k.shortLabel;l.label=g?g:k.label}this.entities={};for(p in e)e[p].origId=p,this.entities[p.toLowerCase()]=e[p];for(p in d)if(!c[p])for(n in l=
d[p],b.useSNameAsId?(this.entities[l.shortLabel.toLowerCase()]=k={},k.origId=l.shortLabel):(this.entities[p.toLowerCase()]=k={},k.origId=p),l)k[n]=l[n]},colorPaletteMap:{basefontcolor:"foregroundcolor",bordercolor:"foregrounddarkcolor",borderalpha:"foregrounddarkalpha",bgcolor:"backgroundlightcolor",bgalpha:"backgroundlightalpha",bgangle:"backgroundlightangle",bgratio:"backgroundlightratio",canvasbordercolor:"foregrounddarkcolor",canvasborderalpha:"foregrounddarkalpha",canvasbgcolor:"backgroundlightcolor",
canvasbgalpha:"backgroundlightalpha",canvasbgangle:"backgroundlightangle",canvasbgratio:"backgroundlightratio",tooltipbordercolor:"foregrounddarkcolor",tooltipborderalpha:"foregrounddarkalpha",tooltipbgcolor:"backgroundlightcolor",tooltipbgalpha:"backgroundlightalpha",tooltipfontcolor:"foregroundcolor",legendbordercolor:"foregrounddarkcolor",legendborderalpha:"foregrounddarkalpha",markerbordercolor:"foregroundlightcolor",markerborderalpha:"foregroundlightalpha",markerbgcolor:"backgrounddarkcolor",
markerbgalpha:"backgrounddarkalpha",markerbgangle:"backgrounddarkangle",markerbgratio:"backgrounddarkratio",plotfillcolor:"backgroundcolor",plotfillalpha:"backgroundalpha",plotfillangle:"backgroundangle",plotfillratio:"backgroundratio",plothoverfillcolor:"backgrounddarkcolor",plothoverfillalpha:"backgrounddarkalpha",plothoverfillangle:"backgrounddarkangle",plothoverfillratio:"backgrounddarkratio",plotbordercolor:"foregroundcolor",plotborderalpha:"foregroundalpha",shadow:"shadow"},eiMethods:{getMapName:function(){return this.jsVars.instanceAPI.name},
getEntityList:function(){var a=this.jsVars.instanceAPI,a=a.hcInstance&&a.hcInstance.entities&&a.hcInstance.entities.items,b=[void 0],d,e,c;for(d in a)e=a[d],c=e.options,b.push({id:e.id,originalId:e.originalId||e.id,active:e.isVisible,lName:c.label,sName:c.shortLabel,value:e.value,formattedValue:e.formattedValue,toolText:e.toolText});return b},getDataAsCSV:function(){var a=this.jsVars.instanceAPI,a=a.hcInstance&&a.hcInstance.entities&&a.hcInstance.entities.items,b='"Id","Short Name","Long Name","Value","Formatted Value"',
d,e,c,g;for(d in a)e=a[d],c=e.options,g=e.value,b+='\r\n"'+e.id+'","'+c.shortLabel+'","'+c.label+'","'+(g===void 0?"":g)+'","'+e.formattedValue+'"';return b},getMapAttribute:function(){var a=this.jsVars.fcObj;aa.raiseWarning(this,"12061210581","run","JavaScriptRenderer~getMapAttribute()",'Use of deprecated "getMapAttribute()". Replace with "getChartAttribute()".');return a.getChartAttribute.apply(a,arguments)},exportMap:function(){var a=this.jsVars.fcObj;aa.raiseWarning(this,"12061210581","run","JavaScriptRenderer~exportMap()",
'Use of deprecated "exportMap()". Replace with "exportChart()".');return a.exportChart&&a.exportChart.apply(a,arguments)}}},$.linebase);za.geo=fa.extendClass(za.line,{type:"geo",simpleSymbol:!0,render:function(){var a=this.chart,b=this.options.animation&&this.animate;if(!a.entities)this.mapGroup=this.group=a.renderer.g("series").add(a.seriesGroup),b&&this.animate(!0),this.processEntityDefs(),this.alignMap(),this.drawEntities(),this.drawTrackers(),this.drawMarkers(),b&&this.animate()},animate:function(a){if(M){var b=
jQuery(this.group.element);a?b.attr({opacity:0}):b.animate({opacity:1},this.options.animation)}},processEntityDefs:function(){var a=this.chart.options,b=a.instanceAPI;b.redefineEntities(b.dataObj.entitydef||[],a.entitydef)},alignMap:function(){var a=this.chart.options,b=a.instanceAPI,a=a[na],d=b._scaleFactor;this.group.align({align:"center",verticalAlign:"middle",width:b.baseWidth*d,height:b.baseHeight*d},!0,{x:a.trackerLeft,y:a.trackerTop,width:a.viewportWidth,height:a.viewportHeight})},setScaleRange:function(a,
b){var f;var d=this.options,e=this.chart,c=e.options[na],g=c.useValuesForMarkers?e.markers:e.entities,e=g.items||g.markerElemObj,c=c.useValuesForMarkers?{show:function(a){g.setMarkerVisibility(!0,a)},hide:function(a){g.setMarkerVisibility(!1,a)}}:{show:function(a){a.show()},hide:function(a){a.hide()}},h=d.data,j=h&&h.length,k;if(d.rangeMin>=a&&d.rangeMax<=b){if(!d.allVisible)this.setVisible(!0),d.allVisible=!0}else if(d.rangeMax<a||d.rangeMin>b){if(!d.allHidden)this.setVisible(!1),d.allHidden=!0}else{d.allVisible=
!1;for(d.allHidden=!1;j--;)d=h[j].id.toLowerCase(),f=(k=e[d])&&k.value,d=f,isNaN(d)||(d&&d>=a&&d<=b?c.show(k):c.hide(k))}},setVisible:function(a){var b=this.chart,d=b.options[na],e=this.legendItem,c=this.visible,g=this.data,h=d.useValuesForMarkers?b.markers:b.entities,j=h.items||h.markerElemObj,d=d.useValuesForMarkers?{"true":function(a){h.setMarkerVisibility(!0,a)},"false":function(a){h.setMarkerVisibility(!1,a)}}:{"true":function(a){a.show()},"false":function(a){a.hide()}};this.visible=a=a===void 0?
!c:a;e&&b.legend.colorizeItem(this,a);for(b=g&&g.length;b--;)e=g[b].id.toLowerCase(),(e=j[e])&&d[a.toString()](e)},drawEntities:function(){var a=this.chart,b=a.options&&a.options.instanceAPI;a.entities=new l(b&&b.dataObj&&b.dataObj.data,a,this.mapGroup)},drawTrackers:function(){this.chart.entities.drawTrackers()},drawMarkers:function(){var a=this.chart,b=(a&&a.options&&a.options.instanceAPI).dataObj;if(b&&b.markers)a.markers=new Ka(b.markers,a)},getAttribs:function(){},getSymbol:function(){},destroy:function(){var a=
this.chart;a.entities&&(a.entities.destroy(),delete a.entities);a.markers&&(a.markers.destroy(),delete a.markers)}})},[3,2,0,"release"]]);
