//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIS.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDIS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ações.
        /// </summary>
        internal static string Ações {
            get {
                return ResourceManager.GetString("Ações", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de inicio real deve ser informada.
        /// </summary>
        internal static string ADataDeInicioRealDeveSerInformada {
            get {
                return ResourceManager.GetString("ADataDeInicioRealDeveSerInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de inicio real deve ser informada!.
        /// </summary>
        internal static string ADataDeInicioRealDeveSerInformada1 {
            get {
                return ResourceManager.GetString("ADataDeInicioRealDeveSerInformada1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de início real deve ser informada para este status de tarefa.
        /// </summary>
        internal static string ADataDeInicioRealDeveSerInformadaParaEsteStatusDeTarefa {
            get {
                return ResourceManager.GetString("ADataDeInicioRealDeveSerInformadaParaEsteStatusDeTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de início real deve ser menor ou igual a data atual!.
        /// </summary>
        internal static string ADataDeInícioRealDeveSerMenorOuIgualADataAtual {
            get {
                return ResourceManager.GetString("ADataDeInícioRealDeveSerMenorOuIgualADataAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de início real não pode ser informada para este status de tarefa.
        /// </summary>
        internal static string ADataDeInicioRealNaoPodeSerInformadaParaEsteStatusDeTarefa {
            get {
                return ResourceManager.GetString("ADataDeInicioRealNaoPodeSerInformadaParaEsteStatusDeTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de término prevista deve ser maior ou igual a data de início.
        /// </summary>
        internal static string ADataDeTérminoPrevistaDeveSerMaiorOuIgualADataDeInicio {
            get {
                return ResourceManager.GetString("ADataDeTérminoPrevistaDeveSerMaiorOuIgualADataDeInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de término prevista deve ser maior ou igual a data de início!.
        /// </summary>
        internal static string ADataDeTérminoPrevistaDeveSerMaiorOuIgualADataDeInício {
            get {
                return ResourceManager.GetString("ADataDeTérminoPrevistaDeveSerMaiorOuIgualADataDeInício", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de término real deve ser menor ou igual à data atual.
        /// </summary>
        internal static string ADataDeTérminoRealDeveSerInformada {
            get {
                return ResourceManager.GetString("ADataDeTérminoRealDeveSerInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de término real deve ser informada!.
        /// </summary>
        internal static string ADataDeTérminoRealDeveSerInformada1 {
            get {
                return ResourceManager.GetString("ADataDeTérminoRealDeveSerInformada1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de término real deve ser maior ou igual a data de início.
        /// </summary>
        internal static string ADataDeTérminoRealDeveSerMaiorOuIgualADataDeInicio {
            get {
                return ResourceManager.GetString("ADataDeTérminoRealDeveSerMaiorOuIgualADataDeInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de término real deve ser maior ou igual a data de início!.
        /// </summary>
        internal static string ADataDeTérminoRealDeveSerMaiorOuIgualADataDeInício {
            get {
                return ResourceManager.GetString("ADataDeTérminoRealDeveSerMaiorOuIgualADataDeInício", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de término real deve ser menor ou igual a data atual.
        /// </summary>
        internal static string ADataDeTérminoRealDeveSerMenorOuIgualADataAtual {
            get {
                return ResourceManager.GetString("ADataDeTérminoRealDeveSerMenorOuIgualADataAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de término real deve ser menor ou igual a data atual!.
        /// </summary>
        internal static string ADataDeTérminoRealDeveSerMenorOuIgualADataAtual1 {
            get {
                return ResourceManager.GetString("ADataDeTérminoRealDeveSerMenorOuIgualADataAtual1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de término real não pode ser informada para este status de tarefa.
        /// </summary>
        internal static string ADataDeTerminoRealNaoPodeSerInformadaParaEsteStatusDeTarefa {
            get {
                return ResourceManager.GetString("ADataDeTerminoRealNaoPodeSerInformadaParaEsteStatusDeTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anotações.
        /// </summary>
        internal static string Anotações {
            get {
                return ResourceManager.GetString("Anotações", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anotações:.
        /// </summary>
        internal static string Anotações_DoisPontos {
            get {
                return ResourceManager.GetString("Anotações_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As informações da empresa informada não foram encontradas no banco de dados (tabela empresa).
        /// </summary>
        internal static string AsInformaçõesDaEmpresaInformadaNãoForamEnc {
            get {
                return ResourceManager.GetString("AsInformaçõesDaEmpresaInformadaNãoForamEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Codigo da Tarefa.
        /// </summary>
        internal static string CodigoDaTarefa {
            get {
                return ResourceManager.GetString("CodigoDaTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Custo Previsto(R$).
        /// </summary>
        internal static string CustoPrevisto {
            get {
                return ResourceManager.GetString("CustoPrevisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Custo Previsto(R$):.
        /// </summary>
        internal static string CustoPrevisto_DoisPontos {
            get {
                return ResourceManager.GetString("CustoPrevisto_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Custo Realizado (R$).
        /// </summary>
        internal static string CustoRealizado {
            get {
                return ResourceManager.GetString("CustoRealizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Custo Realizado (R$):.
        /// </summary>
        internal static string CustoRealizado_DoisPontos {
            get {
                return ResourceManager.GetString("CustoRealizado_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esforço Previsto(h).
        /// </summary>
        internal static string EsforçoPrevistoH {
            get {
                return ResourceManager.GetString("EsforçoPrevistoH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esforço Previsto(h):.
        /// </summary>
        internal static string EsforçoPrevistoH_DoisPontos {
            get {
                return ResourceManager.GetString("EsforçoPrevistoH_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esforço Realizado(h).
        /// </summary>
        internal static string EsforçoRealizadoH {
            get {
                return ResourceManager.GetString("EsforçoRealizadoH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esforço Realizado(h):.
        /// </summary>
        internal static string EsforçoRealizadoH_DoisPontos {
            get {
                return ResourceManager.GetString("EsforçoRealizadoH_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir.
        /// </summary>
        internal static string Incluir {
            get {
                return ResourceManager.GetString("Incluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Início Previsto.
        /// </summary>
        internal static string InícioPrevisto {
            get {
                return ResourceManager.GetString("InícioPrevisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Início Previsto:.
        /// </summary>
        internal static string InícioPrevisto_DoisPontos {
            get {
                return ResourceManager.GetString("InícioPrevisto_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Início Real.
        /// </summary>
        internal static string InícioReal {
            get {
                return ResourceManager.GetString("InícioReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Início Real:.
        /// </summary>
        internal static string InícioReal_DoisPontos {
            get {
                return ResourceManager.GetString("InícioReal_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O custo real não pode ser informado para este status de tarefa.
        /// </summary>
        internal static string OCustoRealNaoPodeSerInformadaParaEsteStatusDeTarefa {
            get {
                return ResourceManager.GetString("OCustoRealNaoPodeSerInformadaParaEsteStatusDeTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O esforço real não pode ser informado para este status de tarefa.
        /// </summary>
        internal static string OEsforcoRealNaoPodeSerInformadoParaEsteStatusDeTarefa {
            get {
                return ResourceManager.GetString("OEsforcoRealNaoPodeSerInformadoParaEsteStatusDeTarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O plano de ação ainda não possui tarefas. Clique no botão &quot;Incluir&quot; para abrir a tela de cadastro..
        /// </summary>
        internal static string OPlanoDeAçãoAindaNãoPossuiTarefasCliqueNoB {
            get {
                return ResourceManager.GetString("OPlanoDeAçãoAindaNãoPossuiTarefasCliqueNoB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a % Concluido.
        /// </summary>
        internal static string PercentualConcluido {
            get {
                return ResourceManager.GetString("PercentualConcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano de Ação:.
        /// </summary>
        internal static string PlanoDeAção_DoisPontos {
            get {
                return ResourceManager.GetString("PlanoDeAção_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Prioridade.
        /// </summary>
        internal static string Prioridade {
            get {
                return ResourceManager.GetString("Prioridade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Prioridade:.
        /// </summary>
        internal static string Prioridade_DoisPontos {
            get {
                return ResourceManager.GetString("Prioridade_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alta.
        /// </summary>
        internal static string PrioridadeAlta {
            get {
                return ResourceManager.GetString("PrioridadeAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Baixa.
        /// </summary>
        internal static string PrioridadeBaixa {
            get {
                return ResourceManager.GetString("PrioridadeBaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Média.
        /// </summary>
        internal static string PrioridadeMédia {
            get {
                return ResourceManager.GetString("PrioridadeMédia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Responsável.
        /// </summary>
        internal static string Responsável {
            get {
                return ResourceManager.GetString("Responsável", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Responsável:.
        /// </summary>
        internal static string Responsável_DoisPontos {
            get {
                return ResourceManager.GetString("Responsável_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente tarefas em execução podem ser excluídas!.
        /// </summary>
        internal static string SomenteTarefasEmExecuçãoPodemSerExcluídas_Exclamacao {
            get {
                return ResourceManager.GetString("SomenteTarefasEmExecuçãoPodemSerExcluídas_Exclamacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status:.
        /// </summary>
        internal static string Status_DoisPontos {
            get {
                return ResourceManager.GetString("Status_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tarefa.
        /// </summary>
        internal static string Tarefa {
            get {
                return ResourceManager.GetString("Tarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tarefa:.
        /// </summary>
        internal static string Tarefa_DoisPontos {
            get {
                return ResourceManager.GetString("Tarefa_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Término Previsto.
        /// </summary>
        internal static string TérminoPrevisto {
            get {
                return ResourceManager.GetString("TérminoPrevisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Término Previsto:.
        /// </summary>
        internal static string TérminoPrevisto_DoisPontos {
            get {
                return ResourceManager.GetString("TérminoPrevisto_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Término Real.
        /// </summary>
        internal static string TérminoReal {
            get {
                return ResourceManager.GetString("TérminoReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Término Real:.
        /// </summary>
        internal static string TérminoReal_DoisPontos {
            get {
                return ResourceManager.GetString("TérminoReal_DoisPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Visualizar em modo ampliado.
        /// </summary>
        internal static string VisualizarEmModoAmpliado {
            get {
                return ResourceManager.GetString("VisualizarEmModoAmpliado", resourceCulture);
            }
        }
    }
}
