//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDIS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        internal static string Alterar {
            get {
                return ResourceManager.GetString("Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A precisão do campo.
        /// </summary>
        internal static string APrecisãoDoCampo {
            get {
                return ResourceManager.GetString("APrecisãoDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade de linhas do campo.
        /// </summary>
        internal static string AQuantidadeDeLinhasDoCampo {
            get {
                return ResourceManager.GetString("AQuantidadeDeLinhasDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As alterações não foram gravadas. É necessário gravar os dados antes de prosseguir com o fluxo..
        /// </summary>
        internal static string AsAlteraçõesNãoForamGravadasÉNecessárioGra {
            get {
                return ResourceManager.GetString("AsAlteraçõesNãoForamGravadasÉNecessárioGra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As informações da empresa informada não foram encontradas no banco de dados (tabela empresa).
        /// </summary>
        internal static string AsInformaçõesDaEmpresaInformadaNãoForamEnc {
            get {
                return ResourceManager.GetString("AsInformaçõesDaEmpresaInformadaNãoForamEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As informações do campo.
        /// </summary>
        internal static string AsInformaçõesDoCampo {
            get {
                return ResourceManager.GetString("AsInformaçõesDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As informações do formulário foram salvas..
        /// </summary>
        internal static string AsInformaçõesDoFormulárioForamSalvas {
            get {
                return ResourceManager.GetString("AsInformaçõesDoFormulárioForamSalvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As opções do campo.
        /// </summary>
        internal static string AsOpçõesDoCampo {
            get {
                return ResourceManager.GetString("AsOpçõesDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção: Não foi possível apresentar o formulário..
        /// </summary>
        internal static string AtençãoNãoFoiPossívelApresentarOFormulário {
            get {
                return ResourceManager.GetString("AtençãoNãoFoiPossívelApresentarOFormulário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variável existeConteudoCampoAlterado não foi definida. Isto deve ser feito na tela responsável por renderizar o formulário.
        /// </summary>
        internal static string AVariávelExisteConteudoCampoAlteradoNãoFoi {
            get {
                return ResourceManager.GetString("AVariávelExisteConteudoCampoAlteradoNãoFoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique no botão à direita para selecionar um novo registro.
        /// </summary>
        internal static string CliqueNoBotãoÀDireitaParaSelecionarUmNovoR {
            get {
                return ResourceManager.GetString("CliqueNoBotãoÀDireitaParaSelecionarUmNovoR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão do registro selecionado?.
        /// </summary>
        internal static string ConfirmaAExclusãoDoRegistroSelecionado {
            get {
                return ResourceManager.GetString("ConfirmaAExclusãoDoRegistroSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to desde.
        /// </summary>
        internal static string desde {
            get {
                return ResourceManager.GetString("desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        internal static string Documentos {
            get {
                return ResourceManager.GetString("Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido!.
        /// </summary>
        internal static string EmailInválido {
            get {
                return ResourceManager.GetString("EmailInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to é menor que a máscara informada.
        /// </summary>
        internal static string éMenorQueAMáscaraInformada {
            get {
                return ResourceManager.GetString("éMenorQueAMáscaraInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao executar o evento AntesSalvar 
        ///.
        /// </summary>
        internal static string ErroAoExecutarOEventoAntesSalvar {
            get {
                return ResourceManager.GetString("ErroAoExecutarOEventoAntesSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao executar o evento AposSalvar 
        ///.
        /// </summary>
        internal static string ErroAoExecutarOEventoAposSalvar {
            get {
                return ResourceManager.GetString("ErroAoExecutarOEventoAposSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        internal static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem campos obrigatórios que não foram preenchidos ou estão no formato incorreto..
        /// </summary>
        internal static string ExistemCamposObrigatóriosQueNãoForamPreenc {
            get {
                return ResourceManager.GetString("ExistemCamposObrigatóriosQueNãoForamPreenc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem subformulários que estão sendo editados..
        /// </summary>
        internal static string ExistemSubformuláriosQueEstãoSendoEditados {
            get {
                return ResourceManager.GetString("ExistemSubformuláriosQueEstãoSendoEditados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string Fechar {
            get {
                return ResourceManager.GetString("Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato Inválido!.
        /// </summary>
        internal static string FormatoInválido {
            get {
                return ResourceManager.GetString("FormatoInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário.
        /// </summary>
        internal static string Formulário {
            get {
                return ResourceManager.GetString("Formulário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário bloqueado para o usuário.
        /// </summary>
        internal static string FormulárioBloqueadoParaOUsuário {
            get {
                return ResourceManager.GetString("FormulárioBloqueadoParaOUsuário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora inválida!.
        /// </summary>
        internal static string HoraInválida {
            get {
                return ResourceManager.GetString("HoraInválida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressão.
        /// </summary>
        internal static string Impressão {
            get {
                return ResourceManager.GetString("Impressão", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        internal static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        internal static string Imprimir1 {
            get {
                return ResourceManager.GetString("Imprimir1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incluir.
        /// </summary>
        internal static string Incluir {
            get {
                return ResourceManager.GetString("Incluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um projeto com o nome informado.
        ///
        ///.
        /// </summary>
        internal static string JáExisteUmProjetoComONomeInformado {
            get {
                return ResourceManager.GetString("JáExisteUmProjetoComONomeInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível prosseguir com a operação!.
        /// </summary>
        internal static string NãoÉPossívelProsseguirComAOperação {
            get {
                return ResourceManager.GetString("NãoÉPossívelProsseguirComAOperação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não está caracterizado.
        /// </summary>
        internal static string nãoEstáCaracterizado {
            get {
                return ResourceManager.GetString("nãoEstáCaracterizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não está caracterizado corretamente.
        /// </summary>
        internal static string nãoEstáCaracterizadoCorretamente {
            get {
                return ResourceManager.GetString("nãoEstáCaracterizadoCorretamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não foi informada corretamente.
        /// </summary>
        internal static string nãoFoiInformadaCorretamente {
            get {
                return ResourceManager.GetString("nãoFoiInformadaCorretamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não foi informado corretamente.
        /// </summary>
        internal static string nãoFoiInformadoCorretamente {
            get {
                return ResourceManager.GetString("nãoFoiInformadoCorretamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não foi informado corretamente ou não está mais disponível.
        /// </summary>
        internal static string nãoFoiInformadoCorretamenteOuNãoEstáMaisDi {
            get {
                return ResourceManager.GetString("nãoFoiInformadoCorretamenteOuNãoEstáMaisDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar o componente ToDoList.
        /// </summary>
        internal static string NãoFoiPossívelEncontrarOComponenteToDoList {
            get {
                return ResourceManager.GetString("NãoFoiPossívelEncontrarOComponenteToDoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to não foram informadas corretamente.
        /// </summary>
        internal static string nãoForamInformadasCorretamente {
            get {
                return ResourceManager.GetString("nãoForamInformadasCorretamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não se aplica.
        /// </summary>
        internal static string NãoSeAplica {
            get {
                return ResourceManager.GetString("NãoSeAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum campo foi definido.
        /// </summary>
        internal static string NenhumCampoFoiDefinido {
            get {
                return ResourceManager.GetString("NenhumCampoFoiDefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo.
        /// </summary>
        internal static string OCampo {
            get {
                return ResourceManager.GetString("OCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do campo.
        /// </summary>
        internal static string OFormatoDoCampo {
            get {
                return ResourceManager.GetString("OFormatoDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formulário possui campo Calculado.
        /// </summary>
        internal static string OFormulárioPossuiCampoCalculado {
            get {
                return ResourceManager.GetString("OFormulárioPossuiCampoCalculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formulário possui campo de lista de opções.
        /// </summary>
        internal static string OFormulárioPossuiCampoDeListaDeOpções {
            get {
                return ResourceManager.GetString("OFormulárioPossuiCampoDeListaDeOpções", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formulário possui campo Lookup.
        /// </summary>
        internal static string OFormulárioPossuiCampoLookup {
            get {
                return ResourceManager.GetString("OFormulárioPossuiCampoLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formulário possui campo Lookup.
        /// </summary>
        internal static string OFormulárioPossuiCampoLookup1 {
            get {
                return ResourceManager.GetString("OFormulárioPossuiCampoLookup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formulário possui campo pré-definido.
        /// </summary>
        internal static string OFormulárioPossuiCampoPréDefinido {
            get {
                return ResourceManager.GetString("OFormulárioPossuiCampoPréDefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formulário precisa ser salvo antes de ser impresso!.
        /// </summary>
        internal static string OFormulárioPrecisaSerSalvoAntesDeSerImpres {
            get {
                return ResourceManager.GetString("OFormulárioPrecisaSerSalvoAntesDeSerImpres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O plano de ação só pode ser definido após as informações da aba.
        /// </summary>
        internal static string OPlanoDeAçãoSóPodeSerDefinidoApósAsInforma {
            get {
                return ResourceManager.GetString("OPlanoDeAçãoSóPodeSerDefinidoApósAsInforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O subformulário do campo.
        /// </summary>
        internal static string OSubformulárioDoCampo {
            get {
                return ResourceManager.GetString("OSubformulárioDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho do campo.
        /// </summary>
        internal static string OTamanhoDoCampo {
            get {
                return ResourceManager.GetString("OTamanhoDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor máximo do campo.
        /// </summary>
        internal static string OValorMáximoDoCampo {
            get {
                return ResourceManager.GetString("OValorMáximoDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor mínimo do campo.
        /// </summary>
        internal static string OValorMínimoDoCampo {
            get {
                return ResourceManager.GetString("OValorMínimoDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano de ação.
        /// </summary>
        internal static string PlanoDeAção {
            get {
                return ResourceManager.GetString("PlanoDeAção", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to precisa ser informado.
        /// </summary>
        internal static string precisaSerInformado {
            get {
                return ResourceManager.GetString("precisaSerInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que não foi especificado durante sua criação.
        /// </summary>
        internal static string queNãoFoiEspecificadoDuranteSuaCriação {
            get {
                return ResourceManager.GetString("queNãoFoiEspecificadoDuranteSuaCriação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que não foi especificado durante sua criação.
        /// </summary>
        internal static string queNãoFoiEspecificadoDuranteSuaCriação1 {
            get {
                return ResourceManager.GetString("queNãoFoiEspecificadoDuranteSuaCriação1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to que não teve o conteúdo definido durante sua criação.
        /// </summary>
        internal static string queNãoTeveOConteúdoDefinidoDuranteSuaCriaç {
            get {
                return ResourceManager.GetString("queNãoTeveOConteúdoDefinidoDuranteSuaCriaç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string SeparadorDecimal {
            get {
                return ResourceManager.GetString("SeparadorDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string SeparadorMilhar {
            get {
                return ResourceManager.GetString("SeparadorMilhar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Só é possível anexar documentos após as informações da aba.
        /// </summary>
        internal static string SóÉPossívelAnexarDocumentosApósAsInformaçõ {
            get {
                return ResourceManager.GetString("SóÉPossívelAnexarDocumentosApósAsInformaçõ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem que fazer uma chamada na Procedure para ler o campo no outro formulário!.
        /// </summary>
        internal static string TemQueFazerUmaChamadaNaProcedureParaLerOCa {
            get {
                return ResourceManager.GetString("TemQueFazerUmaChamadaNaProcedureParaLerOCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terem sido salvas.
        /// </summary>
        internal static string teremSidoSalvas {
            get {
                return ResourceManager.GetString("teremSidoSalvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor não encontrado.
        /// </summary>
        internal static string ValorNãoEncontrado {
            get {
                return ResourceManager.GetString("ValorNãoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violação de chave primária, Entre em contato com o Administrador do Sistema..
        /// </summary>
        internal static string ViolaçãoDeChavePrimáriaEntreEmContatoComOA {
            get {
                return ResourceManager.GetString("ViolaçãoDeChavePrimáriaEntreEmContatoComOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        internal static string Visualizar {
            get {
                return ResourceManager.GetString("Visualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        internal static string Visualizar1 {
            get {
                return ResourceManager.GetString("Visualizar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar o documento.
        /// </summary>
        internal static string VisualizarODocumento {
            get {
                return ResourceManager.GetString("VisualizarODocumento", resourceCulture);
            }
        }
    }
}
