//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIS.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDIS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar.
        /// </summary>
        internal static string Alterar {
            get {
                return ResourceManager.GetString("Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A precisão do campo.
        /// </summary>
        internal static string APrecisãoDoCampo {
            get {
                return ResourceManager.GetString("APrecisãoDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A quantidade de linhas do campo.
        /// </summary>
        internal static string AQuantidadeDeLinhasDoCampo {
            get {
                return ResourceManager.GetString("AQuantidadeDeLinhasDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As alterações não foram gravadas. É necessário gravar os dados antes de prosseguir com o fluxo..
        /// </summary>
        internal static string AsAlteraçõesNãoForamGravadasÉNecessárioGra {
            get {
                return ResourceManager.GetString("AsAlteraçõesNãoForamGravadasÉNecessárioGra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As informações da empresa informada não foram encontradas no banco de dados (tabela empresa).
        /// </summary>
        internal static string AsInformaçõesDaEmpresaInformadaNãoForamEnc {
            get {
                return ResourceManager.GetString("AsInformaçõesDaEmpresaInformadaNãoForamEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As informações do campo.
        /// </summary>
        internal static string AsInformaçõesDoCampo {
            get {
                return ResourceManager.GetString("AsInformaçõesDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As informações do formulário foram salvas..
        /// </summary>
        internal static string AsInformaçõesDoFormulárioForamSalvas {
            get {
                return ResourceManager.GetString("AsInformaçõesDoFormulárioForamSalvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As opções do campo.
        /// </summary>
        internal static string AsOpçõesDoCampo {
            get {
                return ResourceManager.GetString("AsOpçõesDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atenção: Não foi possível apresentar o formulário..
        /// </summary>
        internal static string AtençãoNãoFoiPossívelApresentarOFormulário {
            get {
                return ResourceManager.GetString("AtençãoNãoFoiPossívelApresentarOFormulário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A variável existeConteudoCampoAlterado não foi definida. Isto deve ser feito na tela responsável por renderizar o formulário.
        /// </summary>
        internal static string AVariávelExisteConteudoCampoAlteradoNãoFoi {
            get {
                return ResourceManager.GetString("AVariávelExisteConteudoCampoAlteradoNãoFoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clique no botão à direita para selecionar um novo registro.
        /// </summary>
        internal static string CliqueNoBotãoÀDireitaParaSelecionarUmNovoR {
            get {
                return ResourceManager.GetString("CliqueNoBotãoÀDireitaParaSelecionarUmNovoR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirma a exclusão do registro selecionado?.
        /// </summary>
        internal static string ConfirmaAExclusãoDoRegistroSelecionado {
            get {
                return ResourceManager.GetString("ConfirmaAExclusãoDoRegistroSelecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a desde.
        /// </summary>
        internal static string desde {
            get {
                return ResourceManager.GetString("desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Documentos.
        /// </summary>
        internal static string Documentos {
            get {
                return ResourceManager.GetString("Documentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email inválido!.
        /// </summary>
        internal static string EmailInválido {
            get {
                return ResourceManager.GetString("EmailInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a é menor que a máscara informada.
        /// </summary>
        internal static string éMenorQueAMáscaraInformada {
            get {
                return ResourceManager.GetString("éMenorQueAMáscaraInformada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao executar o evento AntesSalvar 
        ///.
        /// </summary>
        internal static string ErroAoExecutarOEventoAntesSalvar {
            get {
                return ResourceManager.GetString("ErroAoExecutarOEventoAntesSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao executar o evento AposSalvar 
        ///.
        /// </summary>
        internal static string ErroAoExecutarOEventoAposSalvar {
            get {
                return ResourceManager.GetString("ErroAoExecutarOEventoAposSalvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existem campos obrigatórios que não foram preenchidos ou estão no formato incorreto..
        /// </summary>
        internal static string ExistemCamposObrigatóriosQueNãoForamPreenc {
            get {
                return ResourceManager.GetString("ExistemCamposObrigatóriosQueNãoForamPreenc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existem subformulários que estão sendo editados..
        /// </summary>
        internal static string ExistemSubformuláriosQueEstãoSendoEditados {
            get {
                return ResourceManager.GetString("ExistemSubformuláriosQueEstãoSendoEditados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string Fechar {
            get {
                return ResourceManager.GetString("Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato Inválido!.
        /// </summary>
        internal static string FormatoInválido {
            get {
                return ResourceManager.GetString("FormatoInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formulário.
        /// </summary>
        internal static string Formulário {
            get {
                return ResourceManager.GetString("Formulário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formulário bloqueado para o usuário.
        /// </summary>
        internal static string FormulárioBloqueadoParaOUsuário {
            get {
                return ResourceManager.GetString("FormulárioBloqueadoParaOUsuário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hora inválida!.
        /// </summary>
        internal static string HoraInválida {
            get {
                return ResourceManager.GetString("HoraInválida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Impressão.
        /// </summary>
        internal static string Impressão {
            get {
                return ResourceManager.GetString("Impressão", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imprimir.
        /// </summary>
        internal static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imprimir.
        /// </summary>
        internal static string Imprimir1 {
            get {
                return ResourceManager.GetString("Imprimir1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Incluir.
        /// </summary>
        internal static string Incluir {
            get {
                return ResourceManager.GetString("Incluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um projeto com o nome informado.
        ///
        ///.
        /// </summary>
        internal static string JáExisteUmProjetoComONomeInformado {
            get {
                return ResourceManager.GetString("JáExisteUmProjetoComONomeInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível prosseguir com a operação!.
        /// </summary>
        internal static string NãoÉPossívelProsseguirComAOperação {
            get {
                return ResourceManager.GetString("NãoÉPossívelProsseguirComAOperação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a não está caracterizado.
        /// </summary>
        internal static string nãoEstáCaracterizado {
            get {
                return ResourceManager.GetString("nãoEstáCaracterizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a não está caracterizado corretamente.
        /// </summary>
        internal static string nãoEstáCaracterizadoCorretamente {
            get {
                return ResourceManager.GetString("nãoEstáCaracterizadoCorretamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a não foi informada corretamente.
        /// </summary>
        internal static string nãoFoiInformadaCorretamente {
            get {
                return ResourceManager.GetString("nãoFoiInformadaCorretamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a não foi informado corretamente.
        /// </summary>
        internal static string nãoFoiInformadoCorretamente {
            get {
                return ResourceManager.GetString("nãoFoiInformadoCorretamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a não foi informado corretamente ou não está mais disponível.
        /// </summary>
        internal static string nãoFoiInformadoCorretamenteOuNãoEstáMaisDi {
            get {
                return ResourceManager.GetString("nãoFoiInformadoCorretamenteOuNãoEstáMaisDi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível encontrar o componente ToDoList.
        /// </summary>
        internal static string NãoFoiPossívelEncontrarOComponenteToDoList {
            get {
                return ResourceManager.GetString("NãoFoiPossívelEncontrarOComponenteToDoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a não foram informadas corretamente.
        /// </summary>
        internal static string nãoForamInformadasCorretamente {
            get {
                return ResourceManager.GetString("nãoForamInformadasCorretamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não se aplica.
        /// </summary>
        internal static string NãoSeAplica {
            get {
                return ResourceManager.GetString("NãoSeAplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum campo foi definido.
        /// </summary>
        internal static string NenhumCampoFoiDefinido {
            get {
                return ResourceManager.GetString("NenhumCampoFoiDefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo.
        /// </summary>
        internal static string OCampo {
            get {
                return ResourceManager.GetString("OCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formato do campo.
        /// </summary>
        internal static string OFormatoDoCampo {
            get {
                return ResourceManager.GetString("OFormatoDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formulário possui campo Calculado.
        /// </summary>
        internal static string OFormulárioPossuiCampoCalculado {
            get {
                return ResourceManager.GetString("OFormulárioPossuiCampoCalculado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formulário possui campo de lista de opções.
        /// </summary>
        internal static string OFormulárioPossuiCampoDeListaDeOpções {
            get {
                return ResourceManager.GetString("OFormulárioPossuiCampoDeListaDeOpções", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formulário possui campo Lookup.
        /// </summary>
        internal static string OFormulárioPossuiCampoLookup {
            get {
                return ResourceManager.GetString("OFormulárioPossuiCampoLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formulário possui campo Lookup.
        /// </summary>
        internal static string OFormulárioPossuiCampoLookup1 {
            get {
                return ResourceManager.GetString("OFormulárioPossuiCampoLookup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formulário possui campo pré-definido.
        /// </summary>
        internal static string OFormulárioPossuiCampoPréDefinido {
            get {
                return ResourceManager.GetString("OFormulárioPossuiCampoPréDefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O formulário precisa ser salvo antes de ser impresso!.
        /// </summary>
        internal static string OFormulárioPrecisaSerSalvoAntesDeSerImpres {
            get {
                return ResourceManager.GetString("OFormulárioPrecisaSerSalvoAntesDeSerImpres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O plano de ação só pode ser definido após as informações da aba.
        /// </summary>
        internal static string OPlanoDeAçãoSóPodeSerDefinidoApósAsInforma {
            get {
                return ResourceManager.GetString("OPlanoDeAçãoSóPodeSerDefinidoApósAsInforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O subformulário do campo.
        /// </summary>
        internal static string OSubformulárioDoCampo {
            get {
                return ResourceManager.GetString("OSubformulárioDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tamanho do campo.
        /// </summary>
        internal static string OTamanhoDoCampo {
            get {
                return ResourceManager.GetString("OTamanhoDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor máximo do campo.
        /// </summary>
        internal static string OValorMáximoDoCampo {
            get {
                return ResourceManager.GetString("OValorMáximoDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O valor mínimo do campo.
        /// </summary>
        internal static string OValorMínimoDoCampo {
            get {
                return ResourceManager.GetString("OValorMínimoDoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plano de ação.
        /// </summary>
        internal static string PlanoDeAção {
            get {
                return ResourceManager.GetString("PlanoDeAção", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a precisa ser informado.
        /// </summary>
        internal static string precisaSerInformado {
            get {
                return ResourceManager.GetString("precisaSerInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a que não foi especificado durante sua criação.
        /// </summary>
        internal static string queNãoFoiEspecificadoDuranteSuaCriação {
            get {
                return ResourceManager.GetString("queNãoFoiEspecificadoDuranteSuaCriação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a que não foi especificado durante sua criação.
        /// </summary>
        internal static string queNãoFoiEspecificadoDuranteSuaCriação1 {
            get {
                return ResourceManager.GetString("queNãoFoiEspecificadoDuranteSuaCriação1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a que não teve o conteúdo definido durante sua criação.
        /// </summary>
        internal static string queNãoTeveOConteúdoDefinidoDuranteSuaCriaç {
            get {
                return ResourceManager.GetString("queNãoTeveOConteúdoDefinidoDuranteSuaCriaç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        internal static string Salvar {
            get {
                return ResourceManager.GetString("Salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ,.
        /// </summary>
        internal static string SeparadorDecimal {
            get {
                return ResourceManager.GetString("SeparadorDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ..
        /// </summary>
        internal static string SeparadorMilhar {
            get {
                return ResourceManager.GetString("SeparadorMilhar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Só é possível anexar documentos após as informações da aba.
        /// </summary>
        internal static string SóÉPossívelAnexarDocumentosApósAsInformaçõ {
            get {
                return ResourceManager.GetString("SóÉPossívelAnexarDocumentosApósAsInformaçõ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tem que fazer uma chamada na Procedure para ler o campo no outro formulário!.
        /// </summary>
        internal static string TemQueFazerUmaChamadaNaProcedureParaLerOCa {
            get {
                return ResourceManager.GetString("TemQueFazerUmaChamadaNaProcedureParaLerOCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a terem sido salvas.
        /// </summary>
        internal static string teremSidoSalvas {
            get {
                return ResourceManager.GetString("teremSidoSalvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor não encontrado.
        /// </summary>
        internal static string ValorNãoEncontrado {
            get {
                return ResourceManager.GetString("ValorNãoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Violação de chave primária, Entre em contato com o Administrador do Sistema..
        /// </summary>
        internal static string ViolaçãoDeChavePrimáriaEntreEmContatoComOA {
            get {
                return ResourceManager.GetString("ViolaçãoDeChavePrimáriaEntreEmContatoComOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Visualizar.
        /// </summary>
        internal static string Visualizar {
            get {
                return ResourceManager.GetString("Visualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Visualizar.
        /// </summary>
        internal static string Visualizar1 {
            get {
                return ResourceManager.GetString("Visualizar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Visualizar o documento.
        /// </summary>
        internal static string VisualizarODocumento {
            get {
                return ResourceManager.GetString("VisualizarODocumento", resourceCulture);
            }
        }
    }
}
