//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDIS.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDIS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A aba.
        /// </summary>
        internal static string AAba {
            get {
                return ResourceManager.GetString("AAba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário não possui permissão para executar esta ação..
        /// </summary>
        internal static string AAçãoExecutadaNãoProduziuEfeitoENãoFoiPoss {
            get {
                return ResourceManager.GetString("AAçãoExecutadaNãoProduziuEfeitoENãoFoiPoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A ação não pôde ser executada pois o usuário não possui permissão para tal..
        /// </summary>
        internal static string AAçãoNãoPodeSerExecutadaPoisOUsuárioNãoPos {
            get {
                return ResourceManager.GetString("AAçãoNãoPodeSerExecutadaPoisOUsuárioNãoPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ação cancelada pelo usuário..
        /// </summary>
        internal static string AçãoCanceladaPeloUsuário {
            get {
                return ResourceManager.GetString("AçãoCanceladaPeloUsuário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A configuração dos parâmetros para 
        ///        execução de procedimentos no servidor ficou incorreta..
        /// </summary>
        internal static string AConfiguraçãoDosParâmetrosParaExecuçãoDePr {
            get {
                return ResourceManager.GetString("AConfiguraçãoDosParâmetrosParaExecuçãoDePr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A etapa do processo foi alterada por outro usuário.
        ///        Acesse o processo novamente para ver as informações atualizadas.
        /// </summary>
        internal static string AEtapaDoProcessoFoiAlteradaPorOutroUsuário {
            get {
                return ResourceManager.GetString("AEtapaDoProcessoFoiAlteradaPorOutroUsuário", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As informações na base de dados encontram-se inconsistentes..
        /// </summary>
        internal static string AsInformaçõesNaBaseDeDadosEncontramSeIncon {
            get {
                return ResourceManager.GetString("AsInformaçõesNaBaseDeDadosEncontramSeIncon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assinatura digital.
        /// </summary>
        internal static string AssinaturaDigital {
            get {
                return ResourceManager.GetString("AssinaturaDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirma a finalização desta etapa? &lt;br&gt;&lt;br&gt;Opção selecionada:.
        /// </summary>
        internal static string ConfirmaAFinalizaçãoDestaEtapaBrBrOpçãoSel {
            get {
                return ResourceManager.GetString("ConfirmaAFinalizaçãoDestaEtapaBrBrOpçãoSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirma a finalização do preenchimento do(s) formulário(s)?.
        /// </summary>
        internal static string ConfirmaAFinalizaçãoDoPreenchimentoDoSForm {
            get {
                return ResourceManager.GetString("ConfirmaAFinalizaçãoDoPreenchimentoDoSForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirma a tramitação do parecer?.
        /// </summary>
        internal static string ConfirmaATramitaçãoDoParecer {
            get {
                return ResourceManager.GetString("ConfirmaATramitaçãoDoParecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve um erro durante o processamento e não foi possível determinar a causa..
        /// </summary>
        internal static string ErroDuranteOProcessamentoDeCausaIndeterminada {
            get {
                return ResourceManager.GetString("ErroDuranteOProcessamentoDeCausaIndeterminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Etapa Anterior.
        /// </summary>
        internal static string EtapaAnterior {
            get {
                return ResourceManager.GetString("EtapaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Etapa Atual.
        /// </summary>
        internal static string EtapaAtual {
            get {
                return ResourceManager.GetString("EtapaAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Etapa finalizada com sucesso!.
        /// </summary>
        internal static string EtapaFinalizadaComSucesso {
            get {
                return ResourceManager.GetString("EtapaFinalizadaComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existem alterações ainda não salvas.&lt;/br&gt;&lt;/br&gt;Ao pressionar &apos;Ok&apos;, as alterações não salvas serão perdidas!&lt;/br&gt;&lt;/br&gt;Deseja continuar?.
        /// </summary>
        internal static string ExistemAlteraçõesAindaNãoSalvasBrBrAoPress {
            get {
                return ResourceManager.GetString("ExistemAlteraçõesAindaNãoSalvasBrBrAoPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha.
        /// </summary>
        internal static string Falha {
            get {
                return ResourceManager.GetString("Falha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha na execução do procedimento no servidor de banco de dados. (errorcode: {0}:{1}).
        /// </summary>
        internal static string FalhaNaExecuçãoDoProcedimentoNoServidorEnt {
            get {
                return ResourceManager.GetString("FalhaNaExecuçãoDoProcedimentoNoServidorEnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fechar.
        /// </summary>
        internal static string Fechar {
            get {
                return ResourceManager.GetString("Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Finalizar.
        /// </summary>
        internal static string Finalizar {
            get {
                return ResourceManager.GetString("Finalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fluxo.
        /// </summary>
        internal static string Fluxo {
            get {
                return ResourceManager.GetString("Fluxo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Mensagem original do erro: .
        /// </summary>
        internal static string MensagemOriginalDoErro {
            get {
                return ResourceManager.GetString("MensagemOriginalDoErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a na alteração da etapa do processo.
        /// </summary>
        internal static string naAlteraçãoDaEtapaDoProcesso {
            get {
                return ResourceManager.GetString("naAlteraçãoDaEtapaDoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a na definição da próxima etapa do processo.
        /// </summary>
        internal static string naDefiniçãoDaPróximaEtapaDoProcesso {
            get {
                return ResourceManager.GetString("naDefiniçãoDaPróximaEtapaDoProcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a na execução de ações automáticas da etapa do processo.
        /// </summary>
        internal static string naExecuçãoDeAçõesAutomáticasDaEtapaDoProce {
            get {
                return ResourceManager.GetString("naExecuçãoDeAçõesAutomáticasDaEtapaDoProce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a no acionamento de API&apos;s externas configuradas na etapa.
        /// </summary>
        internal static string noAcionamentoDeApisExternasDaEtapa {
            get {
                return ResourceManager.GetString("noAcionamentoDeApisExternasDaEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a no envio de notificações.
        /// </summary>
        internal static string noEnvioDeNotificações {
            get {
                return ResourceManager.GetString("noEnvioDeNotificações", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a no processamento de tempo limite da etapa.
        /// </summary>
        internal static string noProcessamentoDeTempoLimiteDaEtapa {
            get {
                return ResourceManager.GetString("noProcessamentoDeTempoLimiteDaEtapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para prosseguir com o fluxo, é necessário preencher a aba de Critérios!.
        /// </summary>
        internal static string ParaProsseguirComOFluxoÉNecessárioPreenche {
            get {
                return ResourceManager.GetString("ParaProsseguirComOFluxoÉNecessárioPreenche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parecer tramitado com sucesso!.
        /// </summary>
        internal static string ParecerTramitadoComSucesso {
            get {
                return ResourceManager.GetString("ParecerTramitadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a precisa ser salva..
        /// </summary>
        internal static string precisaSerSalva {
            get {
                return ResourceManager.GetString("precisaSerSalva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preenchimento do(s) formulário(s) finalizado com sucesso!.
        /// </summary>
        internal static string PreenchimentoDoSFormulárioSFinalizadoComSu {
            get {
                return ResourceManager.GetString("PreenchimentoDoSFormulárioSFinalizadoComSu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solicitante.
        /// </summary>
        internal static string Solicitante {
            get {
                return ResourceManager.GetString("Solicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tramitar Parecer.
        /// </summary>
        internal static string TramitarParecer {
            get {
                return ResourceManager.GetString("TramitarParecer", resourceCulture);
            }
        }
    }
}
